<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Conceptual Portraits - 1&nbsp; Language</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Language.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Language</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Conceptual Portraits</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Language.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Language</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#language-as-vocabulary" id="toc-language-as-vocabulary" class="nav-link active" data-scroll-target="#language-as-vocabulary"><span class="header-section-number">1.1</span> Language as vocabulary</a></li>
  <li><a href="#sec-naming" id="toc-sec-naming" class="nav-link" data-scroll-target="#sec-naming"><span class="header-section-number">1.2</span> Language as naming</a></li>
  <li><a href="#sec-verbalExpression" id="toc-sec-verbalExpression" class="nav-link" data-scroll-target="#sec-verbalExpression"><span class="header-section-number">1.3</span> Language as verbal expression</a></li>
  <li><a href="#sec-conceptualization" id="toc-sec-conceptualization" class="nav-link" data-scroll-target="#sec-conceptualization"><span class="header-section-number">1.4</span> Language as conceptualization</a></li>
  <li><a href="#sec-construct" id="toc-sec-construct" class="nav-link" data-scroll-target="#sec-construct"><span class="header-section-number">1.5</span> Language as construct</a></li>
  <li><a href="#sec-sound" id="toc-sec-sound" class="nav-link" data-scroll-target="#sec-sound"><span class="header-section-number">1.6</span> Language as sound</a></li>
  <li><a href="#sec-literal" id="toc-sec-literal" class="nav-link" data-scroll-target="#sec-literal"><span class="header-section-number">1.7</span> Language as literal</a></li>
  <li><a href="#sec-nonVerbal" id="toc-sec-nonVerbal" class="nav-link" data-scroll-target="#sec-nonVerbal"><span class="header-section-number">1.8</span> non-verbal language</a></li>
  <li><a href="#documentation" id="toc-documentation" class="nav-link" data-scroll-target="#documentation"><span class="header-section-number">1.9</span> Documentation</a>
  <ul class="collapse">
  <li><a href="#categorization" id="toc-categorization" class="nav-link" data-scroll-target="#categorization"><span class="header-section-number">1.9.1</span> categorization</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Language</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Language is a complex conceptual domain in Sanskrit, as it is testified by the rich array of words that lexicalize it in our corpus, each pointing to a slightly different facet of it. We cover here seven main aspects of Language that are lexicalized in our corpus, language as <strong>vocabulary</strong>, as <strong>naming</strong>, as <strong>sound</strong>, as <strong>literal</strong>, as <strong>conceptualization</strong>, as <strong>construct</strong> and <strong>non-verbal language</strong>. This is no way meant to exhaust all the dimensions of the concept of Language (notable exclusions include meaning and synonymy, expressed by words like <em>artha</em>, <em>abhidheya</em>, <em>adhivacana</em> and <em>paryāya</em>, we may add these in the future), but it constitutes a starting point for the exploration of how this concept is lexically articulated across various layers of our corpus.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LanguageTree.webp" class="img-fluid figure-img" alt="tree graph of lexical field of Language"></p>
<figcaption class="figure-caption">Lexicalization of different aspect of language in our corpus</figcaption>
</figure>
</div>
<p>Overall, the vocabulary used to express the various aspects of Language discussed here remains stable across periods and genres, with the lexical fields expressing the core themes of language as a set of words and language as verbal expression consistently constituting the most prominent share of the lexicon devoted to this conceptual domain. Still, there are some notable shifts, especially in the closely connected areas of language as construct and language as conceptualization, with the former increasing over time and the other one waning. A closer look at the relevant section below (<a href="#sec-construct"><span>Section&nbsp;1.5</span></a>) will reveal that this is due to a shift from an emphasis on language as conceptual construct devoid of ontological foundation, typical of sūtras and early treatises, to a depiction of language as a social construct that functions through agreed conventions of speech, prominent in later philosophical texts, especially from the <em>pramāṇa</em> tradition. Another notable, diachronic change is the sharp decline in the use of <em>nāmadheya</em>, a word strongly associated with early <em>sūtras</em> and <em>prajñāpāramitā</em> discourse (see <a href="#sec-naming"><span>Section&nbsp;1.2</span></a>). There are also some noticeable differences in lexical distribution across genres. Most notably <em>śāstras</em> display a strong preference for <em>śabda</em> among the vocabulary used to convey the idea of ‘word’; and the use of <em>prajñapti</em> in the field of ‘verbal expression’, where it takes the sense of ‘exposition’, is closely connected with vinaya literature.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">by period</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">by genre</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangThemesDiachronicOverview.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">diachronic distribution of different aspects of Language in our corpus, as percentage</figcaption>
</figure>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangThemesGenreOverview.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">distribution of different aspects of Language by genre, as percentage</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>:::</p>
<section id="language-as-vocabulary" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="language-as-vocabulary"><span class="header-section-number">1.1</span> Language as vocabulary</h2>
<p>The very amount of vocables used to express the idea of “word” attests to the many nuances that verbal communication takes on in Sanskrit Buddhist literature. <strong><em>Nāman</em></strong>, which perhaps is closest to the English “word” points to the generic ability of language to signify things.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> <strong><em>Pada</em></strong> adds a grammatical nuance and captures inflected words as the basic unit of speech which, since they include compound forms, are able to signify not only a thing but also its qualities.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> <strong><em>Vacana</em></strong> picks up on the communicative aspect of words,<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> often with an emphasis on their authoritative status (<em>buddhavacana</em>). <strong><em>Śabda</em></strong> echoes the audible aspect of words, and it is especially used in glosses, which picked on words as audible, given that texts were traditionally recited and learned through listening.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> <strong><em>Ruta</em></strong> also denotes the audible aspect of words. In this case, the association of audible words with recitation and verbatim quotation lends <em>ruta</em> the meaning of ‘words taken literally’.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> <strong><em>Samjñā</em></strong>, which is perhaps closer to English “name” or “term” than “word”, highlights the interface between concepts and the lexicon used to denote them, emphasising the aspect of words as labels for notions.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> <strong><em>Prajñapti</em></strong> emphasises the practically useful but ontologically unfounded nature of words.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> <strong><em>Saṃketa</em></strong> captures the socially constructed, conventional, nature of words.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p><strong><em>Śabda</em></strong> is by far the lemma most frequently used in the sense of “word” in our corpus. But is an artefact of the preponderance of <em>śāstra</em> literature in our corpus and it is due to <em>śabda’s</em> role in introducing glosses in commentaries. The lemma most typically used in the sense of word across all genres is <strong><em>pada</em></strong>, followed by <strong><em>nāman</em></strong>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">frequency</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">by genre</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false">% by genre</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false">table</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LanguageAsVocabulary.webp" class="img-fluid figure-img" alt="nāman=2610;pada=3553;ruta=88;śabda=6497;saṃjñā=2317;saṃketa=861;vacana=3030"></p>
<figcaption class="figure-caption">absolute frequency of each lemma in the lexical field of vocabulary</figcaption>
</figure>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LanguageAsVocabuaryByGenre.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">absolute frequency of each lemma in the lexical field of vocabulary, by genre</figcaption>
</figure>
</div>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LanguageAsVocabuaryPercByGenre.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">frequency of each lemma in the lexical field of vocabulary as percent of total by genre</figcaption>
</figure>
</div>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>frequency of words meaning word, by genre</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">lemma</th>
<th style="text-align: center;">avadāna</th>
<th style="text-align: center;">dhāraṇī</th>
<th style="text-align: center;">lit</th>
<th style="text-align: center;">sādhana</th>
<th style="text-align: center;">śāstra</th>
<th style="text-align: center;">stotra</th>
<th style="text-align: center;">sūtra</th>
<th style="text-align: center;">tantra</th>
<th style="text-align: center;">vinaya</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">nāman</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">871</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1,597</td>
<td style="text-align: center;">87</td>
<td style="text-align: center;">40</td>
</tr>
<tr class="even">
<td style="text-align: center;">pada</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1,935</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">743</td>
<td style="text-align: center;">222</td>
<td style="text-align: center;">29</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ruta</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">29</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">śabda</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6,126</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">251</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">saṃjñā</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">417</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">198</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">42</td>
</tr>
<tr class="even">
<td style="text-align: center;">saṃketa</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">vacana</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">173</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-naming" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="sec-naming"><span class="header-section-number">1.2</span> Language as naming</h2>
<p>The naming aspect of language is mainly lexicalized by <em><strong>nāman</strong>, <strong>saṃjñā</strong>, <strong>ākhyāta</strong>, <strong>saṃketa</strong></em> and <strong><em>nāmadheya</em></strong>. <em>Nāman</em> is overall the most prototypical word in this sense, as this sense is also central to its semantic spectrum. <em>Saṃjñā</em>, especially when used in <em>bahuvrīhi</em> constructions to mean “called”, is also a prominent vocable in this area, although in Buddhist literature this is not its most prototypical sense. <em>Nāmadheya</em> is closely associated to sūtra literature, especially of <em>prajñāpāramitā</em> tradition, and consequently its use sharply declines with time.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">near-synonyms analysis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Parallel patterns of near-synonymy in other languages</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p><strong>Nāman</strong> features across the broadest range of contexts, from mundane personal naming to philosophical discussions. It appears as the most concrete and practical word for names, and especially for names as social identifiers. In our corpus <em>nāman</em> is used in this sense in contexts of personal naming and identification. For example, <em>Mahāvastu</em><strong>,</strong> 10333 presents <strong>“</strong><em>bhavanto kumārasya sadṛśaṃ nāmaṃ karotha</em>” (“Sirs, give a fitting name to the boy.” Jones II 375), while <em>Ratnamālāvadāna</em>, 1276 shows “<em>kṛtvā jātimahaṃ nāma sthāpituṃ saṃvabhāṣire /</em>” (“Having performed a birth ceremony, they spoke to establish a name.” [machine-translated with Dharmamitra]). In <code>scriptures</code> and <code>philosophical contexts</code>, it is often used to denote naming the objects of experience, in which case it often appears with the other near-synonyms discussed here, as in the <em>Pañcaviṃśatisāhasrikāprajñāpāramitā</em>, 17602 “a-nāmakāt sarva-dharmān nāma-saṃketena deśayat^īdaṃ rūpam ime vedanā-saṃjñā-saṃskārā /” where the Buddha teaches all phenomena “through names and conventional signs.”</p>
<p><strong>Saṃjñā</strong> denotes the basic cognitive act of designation or conceptual recognition. In our corpus, it frequently appears in contexts where names arise naturally from circumstances or consensus, as in the <em>Vinayavastu</em>,11922 “<em>agāram agāram iti saṃjñā udapādi</em>” (“the designation ‘house’ arose”), and <em>Vinayavastu,</em> 11964 “<em>mahāsaṃmato mahāsaṃmata iti saṃjñ^odapādi</em>” (“The designation ‘Mahāsammata, Mahāsammata’ arose” [machine-translated with Dharmamitra]). Here saṃjñā carries a sense of immediate cognitive recognition and categorization and in this sense it is close to cases where it lexicalizes the interface between vocabulary, the way things are called, and notions, the way things are conceptualized, as in e.g.&nbsp;<em>Divyāvadāna</em>, 12692 “<em>saṃjñā-mātrakam idaṃ lokasya yad idam ucyate brāhmaṇa iti vā kṣatriya iti vā vaiśya iti vā śūdra iti vā</em>” (“What is called a Brāhmaṇa, Kṣatriya, Vaiśya, or Śūdra in this world is merely a conventional designation.” [machine-translated with Dharmamitra]) (see section Language as conceptualization below).</p>
<p><strong>Ākhyāta</strong> functions quite differently, emphasizing the act of declaration, often by an authority figure. The corpus reveals its frequent use in religious contexts where Buddha or other teachers make authoritative statements. In <em>Pañcaviṃśatisāhasrikāprajñāpāramitā</em><strong>,</strong> 12752 “<em>pañca subhūte skandhās tathāgatena loka ākhyātaḥ</em>” (“Subhūti, the five aggregates are proclaimed as the world by the Tathāgata.” [machine-translated with Dharmamitra]), we see ākhyāta used for authoritative religious teaching. <em>Divyāvadāna</em>, 3900 similarly shows “<em>tathāgato arhan samyaksambuddhas teṣāṃ sattvānām agra ākhyātaḥ</em>” (“Among those beings … a perfectly awakened tathāgata arhat is said to be the best.” [Rotman]), emphasizing official recognition or proclamation.</p>
<p><strong>Saṃketa</strong> emphasises the socially agreed nature of names and often appears in discussions about the conventional or arbitrary nature of linguistic signs. Prajñāpāramitā literature frequently uses it to emphasize the merely conventional status of names. <em>Pañcaviṃśatisāhasrikāprajñāpāramitā</em>, 2496 states “<em>anyatra nāma-saṃketa-mātreṇa vyavahriyate</em>” (“Elsewhere, it is merely designated by a conventional name.” [machine-translated with Dharmamitra]), highlighting the arbitrary relationship between signs and their referents. This term consistently appears in contexts questioning the ultimate reality of linguistic designations.</p>
<p><strong>Nāmadheya</strong> functions as a formal, ceremonial term for naming, particularly in ritual or official contexts. In our corpus it frequently features in the context of birth ceremonies and formal designations. <em>Vinayavastu</em>, 10730 describes “<em>jātimahaṃ kṛtvā nāmadheyaṃ vyavasthāpyate /</em>” (“After performing the birth ceremony, a name is bestowed.” [machine-translated with Dharmamitra]), while <em>Lalitavistara</em>, 1337 shows “<em>kim ahaṃ kumārasya nāmadheyaṃ kariṣyāmi iti /</em>” (“‘Now, what shall I name my young son?’” [Dahl et al.&nbsp;&amp; 84000: Translating the Words of the Buddha]). The term carries connotations of formality and ceremonial importance.</p>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<p><code>CAUTION: the following content is AI-generated with Claude Sonnet 4 and has not been reviewed.</code></p>
<p>The sophisticated distinctions found in Buddhist Sanskrit reflect a broader cross-linguistic tendency to develop nuanced vocabularies for naming and designation. Several language families display remarkably similar patterns:</p>
<section id="classical-greek-authority-and-convention" class="level4" data-number="1.2.0.1">
<h4 data-number="1.2.0.1" class="anchored" data-anchor-id="classical-greek-authority-and-convention"><span class="header-section-number">1.2.0.1</span> Classical Greek: Authority and Convention</h4>
<p>Ancient Greek exhibits parallel distinctions with <strong>ὄνομα</strong> (onoma) as the basic term for “name,” <strong>κλῆσις</strong> (klēsis) for “calling/designation,” <strong>ἐπωνυμία</strong> (epōnymia) for formal naming after someone, and <strong>προσηγορία</strong> (prosēgoria) for appellations or titles. Philosophical contexts, particularly in Plato and Aristotle, distinguish between <strong>θέσις</strong> (thesis) - conventional naming by agreement - and <strong>φύσις</strong> (physis) - natural naming, paralleling the Sanskrit saṃketa’s emphasis on conventionality versus inherent designation.</p>
</section>
<section id="classical-chinese-ritual-and-social-hierarchy" class="level4" data-number="1.2.0.2">
<h4 data-number="1.2.0.2" class="anchored" data-anchor-id="classical-chinese-ritual-and-social-hierarchy"><span class="header-section-number">1.2.0.2</span> Classical Chinese: Ritual and Social Hierarchy</h4>
<p>Classical Chinese demonstrates sophisticated naming distinctions: <strong>名</strong> (míng) serves as the basic term for name, <strong>號</strong> (hào) indicates formal titles or designations, <strong>字</strong> (zì) refers to courtesy names, <strong>諡</strong> (shì) denotes posthumous names, and <strong>稱</strong> (chēng) means “to call/designate.” The Confucian concept of <strong>正名</strong> (zhèngmíng) - “rectification of names” - emphasizes the moral and social importance of proper designation, similar to how Buddhist Sanskrit treats naming as philosophically significant.</p>
</section>
<section id="arabic-sacred-and-secular-naming" class="level4" data-number="1.2.0.3">
<h4 data-number="1.2.0.3" class="anchored" data-anchor-id="arabic-sacred-and-secular-naming"><span class="header-section-number">1.2.0.3</span> Arabic: Sacred and Secular Naming</h4>
<p>Arabic displays parallel complexity with <strong>اسم</strong> (ism) as the fundamental term for name, <strong>لقب</strong> (laqab) for epithets or nicknames, <strong>كنية</strong> (kunya) for teknonyms, <strong>نسبة</strong> (nisba) for relational names, and <strong>دعوة</strong> (da’wa) for calling or designation. Islamic theological contexts distinguish between <strong>الأسماء الحسنى</strong> (al-asmā’ al-ḥusnā) - the beautiful names of God - and ordinary human naming, reflecting the Sanskrit distinction between authoritative (ākhyāta) and conventional (saṃketa) designation.</p>
</section>
<section id="latin-legal-and-religious-formality" class="level4" data-number="1.2.0.4">
<h4 data-number="1.2.0.4" class="anchored" data-anchor-id="latin-legal-and-religious-formality"><span class="header-section-number">1.2.0.4</span> Latin: Legal and Religious Formality</h4>
<p>Latin exhibits similar patterns with <strong>nomen</strong> (basic name), <strong>cognomen</strong> (family name), <strong>praenomen</strong> (personal name), <strong>appellatio</strong> (designation/calling), and <strong>denominatio</strong> (formal naming). Legal and religious contexts distinguish between <strong>nomen proprium</strong> (proper name) and <strong>nomen appellativum</strong> (common designation), paralleling Sanskrit distinctions between formal nāmadheya and conventional saṃjñā.</p>
</section>
<section id="japanese-social-stratification-in-naming" class="level4" data-number="1.2.0.5">
<h4 data-number="1.2.0.5" class="anchored" data-anchor-id="japanese-social-stratification-in-naming"><span class="header-section-number">1.2.0.5</span> Japanese: Social Stratification in Naming</h4>
<p>Japanese shows remarkable complexity with <strong>名前</strong> (namae) for basic names, <strong>名称</strong> (meishō) for formal designations, <strong>呼び名</strong> (yobina) for what someone is called, <strong>通称</strong> (tsūshō) for common names, and <strong>称号</strong> (shōgō) for titles. The honorific system creates additional layers with <strong>尊称</strong> (sonshō) for respectful designations, reflecting social hierarchy similar to how Sanskrit terms encode different levels of formality and authority.</p>
</section>
<section id="hebrew-sacred-and-profane-distinction" class="level4" data-number="1.2.0.6">
<h4 data-number="1.2.0.6" class="anchored" data-anchor-id="hebrew-sacred-and-profane-distinction"><span class="header-section-number">1.2.0.6</span> Hebrew: Sacred and Profane Distinction</h4>
<p>Biblical and Rabbinic Hebrew distinguishes <strong>שם</strong> (shem) as the basic term for name, <strong>קריאה</strong> (qeri’ah) for calling/designation, <strong>כינוי</strong> (kinnuy) for epithets, and <strong>תואר</strong> (to’ar) for titles. The theological significance of divine names creates special categories like <strong>שם המפורש</strong> (shem ha-meforash) - the explicit name of God - versus ordinary human names, paralleling Sanskrit’s recognition of different types of authoritative designation. Germanic Languages: Compound Complexity</p>
<p>The sophisticated distinctions found in Buddhist Sanskrit reflect a broader cross-linguistic tendency to develop nuanced vocabularies for naming and designation. Several language families display remarkably similar patterns:</p>
</section>
<section id="classical-greek-authority-and-convention-1" class="level4" data-number="1.2.0.7">
<h4 data-number="1.2.0.7" class="anchored" data-anchor-id="classical-greek-authority-and-convention-1"><span class="header-section-number">1.2.0.7</span> Classical Greek: Authority and Convention</h4>
<p>Ancient Greek exhibits parallel distinctions with <strong>ὄνομα</strong> (onoma) as the basic term for “name,” <strong>κλῆσις</strong> (klēsis) for “calling/designation,” <strong>ἐπωνυμία</strong> (epōnymia) for formal naming after someone, and <strong>προσηγορία</strong> (prosēgoria) for appellations or titles. Philosophical contexts, particularly in Plato and Aristotle, distinguish between <strong>θέσις</strong> (thesis) - conventional naming by agreement - and <strong>φύσις</strong> (physis) - natural naming, paralleling the Sanskrit saṃketa’s emphasis on conventionality versus inherent designation.</p>
</section>
<section id="classical-chinese-ritual-and-social-hierarchy-1" class="level4" data-number="1.2.0.8">
<h4 data-number="1.2.0.8" class="anchored" data-anchor-id="classical-chinese-ritual-and-social-hierarchy-1"><span class="header-section-number">1.2.0.8</span> Classical Chinese: Ritual and Social Hierarchy</h4>
<p>Classical Chinese demonstrates sophisticated naming distinctions: <strong>名</strong> (míng) serves as the basic term for name, <strong>號</strong> (hào) indicates formal titles or designations, <strong>字</strong> (zì) refers to courtesy names, <strong>諡</strong> (shì) denotes posthumous names, and <strong>稱</strong> (chēng) means “to call/designate.” The Confucian concept of <strong>正名</strong> (zhèngmíng) - “rectification of names” - emphasizes the moral and social importance of proper designation, similar to how Buddhist Sanskrit treats naming as philosophically significant.</p>
</section>
<section id="arabic-sacred-and-secular-naming-1" class="level4" data-number="1.2.0.9">
<h4 data-number="1.2.0.9" class="anchored" data-anchor-id="arabic-sacred-and-secular-naming-1"><span class="header-section-number">1.2.0.9</span> Arabic: Sacred and Secular Naming</h4>
<p>Arabic displays parallel complexity with <strong>اسم</strong> (ism) as the fundamental term for name, <strong>لقب</strong> (laqab) for epithets or nicknames, <strong>كنية</strong> (kunya) for teknonyms, <strong>نسبة</strong> (nisba) for relational names, and <strong>دعوة</strong> (da’wa) for calling or designation. Islamic theological contexts distinguish between <strong>الأسماء الحسنى</strong> (al-asmā’ al-ḥusnā) - the beautiful names of God - and ordinary human naming, reflecting the Sanskrit distinction between authoritative (ākhyāta) and conventional (saṃketa) designation.</p>
</section>
<section id="latin-legal-and-religious-formality-1" class="level4" data-number="1.2.0.10">
<h4 data-number="1.2.0.10" class="anchored" data-anchor-id="latin-legal-and-religious-formality-1"><span class="header-section-number">1.2.0.10</span> Latin: Legal and Religious Formality</h4>
<p>Latin exhibits similar patterns with <strong>nomen</strong> (basic name), <strong>cognomen</strong> (family name), <strong>praenomen</strong> (personal name), <strong>appellatio</strong> (designation/calling), and <strong>denominatio</strong> (formal naming). Legal and religious contexts distinguish between <strong>nomen proprium</strong> (proper name) and <strong>nomen appellativum</strong> (common designation), paralleling Sanskrit distinctions between formal nāmadheya and conventional saṃjñā.</p>
</section>
<section id="japanese-social-stratification-in-naming-1" class="level4" data-number="1.2.0.11">
<h4 data-number="1.2.0.11" class="anchored" data-anchor-id="japanese-social-stratification-in-naming-1"><span class="header-section-number">1.2.0.11</span> Japanese: Social Stratification in Naming</h4>
<p>Japanese shows remarkable complexity with <strong>名前</strong> (namae) for basic names, <strong>名称</strong> (meishō) for formal designations, <strong>呼び名</strong> (yobina) for what someone is called, <strong>通称</strong> (tsūshō) for common names, and <strong>称号</strong> (shōgō) for titles. The honorific system creates additional layers with <strong>尊称</strong> (sonshō) for respectful designations, reflecting social hierarchy similar to how Sanskrit terms encode different levels of formality and authority.</p>
</section>
<section id="hebrew-sacred-and-profane-distinction-1" class="level4" data-number="1.2.0.12">
<h4 data-number="1.2.0.12" class="anchored" data-anchor-id="hebrew-sacred-and-profane-distinction-1"><span class="header-section-number">1.2.0.12</span> Hebrew: Sacred and Profane Distinction</h4>
<p>Biblical and Rabbinic Hebrew distinguishes <strong>שם</strong> (shem) as the basic term for name, <strong>קריאה</strong> (qeri’ah) for calling/designation, <strong>כינוי</strong> (kinnuy) for epithets, and <strong>תואר</strong> (to’ar) for titles. The theological significance of divine names creates special categories like <strong>שם המפורש</strong> (shem ha-meforash) - the explicit name of God - versus ordinary human names, paralleling Sanskrit’s recognition of different types of authoritative designation.</p>
</section>
<section id="germanic-languages" class="level4" data-number="1.2.0.13">
<h4 data-number="1.2.0.13" class="anchored" data-anchor-id="germanic-languages"><span class="header-section-number">1.2.0.13</span> Germanic Languages</h4>
<p>Old Norse and Old High German developed rich compound systems: Old Norse <strong>nafn</strong> (name), <strong>heiti</strong> (designation), <strong>kenning</strong> (metaphorical name), and <strong>viðrnafn</strong> (additional name). These languages often encode the circumstances or authority of naming within compound structures, similar to how Sanskrit nāmadheya encodes ceremonial context.</p>
</section>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">frequency</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">by genre</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-3" role="tab" aria-controls="tabset-4-3" aria-selected="false">% by genre</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-4" role="tab" aria-controls="tabset-4-4" aria-selected="false">% by period</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-5" role="tab" aria-controls="tabset-4-5" aria-selected="false">table</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangAsNaming.webp" class="img-fluid figure-img" alt="ākhyāta=87;nāmadheya=1304;nāman=1618;saṃjñā=802;saṃketa=874"></p>
<figcaption class="figure-caption">Language as naming, absolute freq</figcaption>
</figure>
</div>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangAsNamingByGenre.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Language as naming, absolute freq by genre</figcaption>
</figure>
</div>
</div>
<div id="tabset-4-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-3-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangAsNamePerc.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Language as naming, percent by genre</figcaption>
</figure>
</div>
</div>
<div id="tabset-4-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-4-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangAsNamingPercByPeriod.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Language as naming, percent by genre</figcaption>
</figure>
</div>
</div>
<div id="tabset-4-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-5-tab">
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>frequency of words meaning word, by genre</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">lemma</th>
<th style="text-align: center;">avadāna</th>
<th style="text-align: center;">dhāraṇī</th>
<th style="text-align: center;">lit</th>
<th style="text-align: center;">sādhana</th>
<th style="text-align: center;">śāstra</th>
<th style="text-align: center;">stotra</th>
<th style="text-align: center;">sūtra</th>
<th style="text-align: center;">tantra</th>
<th style="text-align: center;">vinaya</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">ākhyāta</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">nāmadheya</td>
<td style="text-align: center;">119</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">69</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1,057</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">40</td>
</tr>
<tr class="odd">
<td style="text-align: center;">nāman</td>
<td style="text-align: center;">429</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">194</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">361</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">335</td>
<td style="text-align: center;">77</td>
<td style="text-align: center;">98</td>
</tr>
<tr class="even">
<td style="text-align: center;">saṃjñā</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">418</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">219</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">55</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-verbalExpression" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="sec-verbalExpression"><span class="header-section-number">1.3</span> Language as verbal expression</h2>
<p>Several words are used to convey the general idea of language as verbal expression, ranging from speech to statement to the pronounciation of individual syllables. Chief among them are <strong><em>vāc</em></strong>, <strong><em>vacana</em></strong>, <strong><em>abhilāpa</em></strong>, <strong><em>prajñapti</em></strong>, <strong><em>ākhyāta</em></strong>, <strong><em>pada</em></strong> and <strong><em>akṣara</em></strong>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">near-synonym analysis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Parallel patterns of near-synonymy in other languages</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<p><strong>Vāc</strong> is perhaps the most prototypical word in denoting speech in Buddhist literature, especially in sūtras. It denotes speech as an action, as in <em>Suvikrāntavikrāmiparipṛcchā</em>, 247: “<em>na hi vāk-karmaṇā bodhiḥ prāpyate</em>” (“For it is not by a deed of speech that one can attain enlightenment […].” [Conze 13]) and also typically in the triad kāya-vāk-manas, such as <em>Guṇakāraṇḍavyūhasūtra</em>, 1695: “<em>kāya-vāco-manas-karma śodhayiṣyāmi sarvathā</em>” (“I shall purify all actions of body, speech, and mind in every way.” [machine-translated with Dharmamitra]); or, in less doctrinal context, <em>Buddhacarita</em>, 702: “<em>prakīrṇa-vācaḥ pathi maunam īyuḥ</em> /” (“[…] those chattering on the road fell silent upon seeing him.” [Olivelle 281]).</p>
<p><strong>Vacana</strong> is another prototypical word for speech, especially in <em>śāstra</em> and <em>avadāna</em>. In contrast with <em>vāc</em>, which primarily emphasises the action of speaking, <em>vacana</em> foregrounds the content of what is said. It can denote all kinds of speech, including negatively charged one, as in <em>Śikṣāsamuccaya</em>, 126: “<em>para-varṇa-pratigha-vacanā vā /</em>” (“… or words harmful to the reputation of others, …” [Goodman 123), however more typically it denotes authoritative speech. It often occurs in contexts of doctrinal teaching, especially in the compound <em>buddhavacana</em>, such as <em>Bodhisattvabhūmi</em>,&nbsp;2788: “<em>tathā hi bodhisattvena tīrthika-śāstreṣv api tāvad yogaḥ karaṇīyaḥ prāg eva buddha-vacane /</em>” (“Since a bodhisattva should even strive to learn heretical treatises, how much more so should he or she [study teachings that are] the word of the Buddha.” [Engle]) and similar collocations, as in <em>Samādhirāja</em>, 129: “<em>sarvaṃ c^āsya vacanaṃ buddha-parigṛhītaṃ niścarati //</em>” (“And all his words emerge as accepted by the Buddha.” [machine-translated with Dharmamitra]).</p>
<p><strong>Ākhyāta</strong> also foregrounds statements as authoritative proclamations, but shifts the emphasis to role of the statement in revealing some otherwise hidden truth, as in <em>Larger Sukhāvatīvyūha</em>,&nbsp;64: “<em>ākhyāt^ājita mayā pūrva-kuśala-mūla-pārami-prāptiḥ /</em>”&nbsp;(“And I have proclaimed, Ajita, the way to gain the perfection of past roots of merit.” [Gómez 109]). The <em>Guṇakāraṇḍavyūhasūtra</em> repeatedly uses “<em>ity ākhyātaṃ mun-^īśvaraiḥ</em>” (“Thus it has been taught by the lords of sages.” [machine-translated with Dharmamitra]), establishing its association with authoritative religious pronouncement.</p>
<p><strong>Prajñapti</strong> in this sense refers primarily to the instructions of teachers and formulations of monastic rules, which makes it strongly associated with <code>vinaya</code> literature. The <em>Abhidharmakośabhāṣya,</em> 7084 states “<em>kathaṃ tāvad eṣām upāsaka-saṃvar-^ādīnām aṅga-pratiniyamo bhavati / śāstṛ-prajñapti-vaśāt /</em>” (“Answer: How can we know the extent, the number of the rules of the disciplines of the Upasaka, the Sramanera, or the Bhiksu? Evidently through the teaching of the Master.” [Pruden 600]). This use of prajñapti is typical of the vinaya, <em>Bhikṣuṇīvinaya</em>,&nbsp;1799: “<em>saṃghātiśeṣan ti saṃghātiśeṣāye āpattīye saṃkāṣanā prakāśanā vivaraṇā vibhajanā uttānīkarmatā&nbsp;prajñaptiḥ /</em>”&nbsp;(“La faute réparable par procédure donne lieu à élucidation, explication, éclaircissement, analyse, déclaration, promulgation.” [Nolot 91]).</p>
<p><strong>Abhilāpa</strong>’s semantic focus is on verbal articulation and inexpressability. This is best captured by its cognate <em>abhilapya</em>, which is typically negated to signify the inexpressability of reality. <em>Abhilāpa</em> is also used in this way, as in <em>Suvikrāntavikrāmiparipṛcchā</em>,&nbsp;1103: “<em>eṣ^aiv^ātra āyuṣman śāradvatī-putra prajñāpāramitā yo ’vyāhāraḥ; an-udāhāraḥ ; an-abhihāraḥ ; an-abhilāpaḥ /</em>”&nbsp;(“This perfection of wisdom in fact lies outside all conventional discourse, it is unutterable, unpronounceable, it cannot be talked about.” [Conze 43]), and it is typically associated with <code>philosophical discourse</code> about the gap between reality and what is verbally expressible, both in sūtra and scholastic literature, where it is also associated with the conceptual construction of reality, as in <em>Nyāyabindu</em>, 5: “abhilāpa-saṃsarga-yogya pratibhāsā pratītiḥ kalpanā” (“Conceptualization is the apprehension of an appearance that is suitable for verbal association.” [machine-translated with Dharmamitra]). However, abhilāpa can also convey the idea of verbally articulating anything, including the Dharma “<em>etarhi ca mam^aiv^edam upāya-kauśalyaṃ dharma-deśan-^ābhilāpena yad yūyam etarhi nirvāṇam iti manyadhve /</em>” [<em>Saddharmapuṇḍarīka</em>,&nbsp;2347] (“In this you have to see an able device of mine that from the expressions used by me, in preaching the law, you fancy Nirvana to take place at this moment.” [Kern 202]).</p>
<p><strong>Pada</strong> serves as the fundamental building block of meaningful discourse, consistently referring to words, verses, or linguistic units. A typical collocation in this sense is <em>arthapada</em>, e.g.&nbsp;<em>Samādhirāja</em>, 3000 “<em>vyākari nāyaku āśayu jñātvā artha-padeṣu su-śikṣita-śāstā / deśayi śānta samādhi nar-^endras tatrimi artha-padāni śṛṇotha</em>”, where the teacher is described as well-trained in meaningful words, or <em>Bodhisattvabhūmi</em>,&nbsp;5880: “<em>gambhīraṃ c ^ārtha-padaṃ&nbsp;prajñayā pratividhya kālena kālaṃ saṃprakāśayati /</em>” (“Having fathomed statements of profound meaning with his or her wisdom, he or she reveals them [to others] at appropriate times.” [Engle]).</p>
<p><strong>Akṣara</strong> operates at the most granular level as syllables or letters. In contrast with <em>vyañjana</em> (see Language as literal below), akṣara foregrounds the uttered, pronounced dimension of syllables and it often features in the <code>context of mantra recitation</code>, as in <em>Śikṣāsamuccaya</em>,&nbsp;6029: “<em>atra ca mantrāṇām a-jñānān n ^ādhik-^ākṣara-pāṭhe doṣo asti /</em>”&nbsp;(“If, due to ignorance of the mantras, you recite additional syllables, there is no problem.” [Goodman 135]), or <em>Divyāvādana</em>, 13056: “catur-viṃśaty-akṣarā sāvitrī” (“The Sāvitrī verse consists of twenty-four syllables.” [machine-translated with Dharmamitra]).</p>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<p><code>CAUTION: the following content is AI-generated with Claude Sonnet 4 and has not been reviewed.</code></p>
<p>The sophisticated near-synonymy patterns observed in Buddhist Sanskrit find remarkable parallels across multiple language families, suggesting shared tendencies in how humans conceptualize and categorize verbal expression.</p>
<p>####Classical Greek: Philosophical Precision</p>
<p>Ancient Greek displays perhaps the most striking parallel to Sanskrit’s semantic granularity. The domain includes logos (reasoned discourse, cosmic principle), lexis (style of speaking, diction), rhema (utterance, verb), onoma (name, noun), phone (voice, sound), mythos (narrative speech), and epos (word, epic speech). Like Sanskrit’s system, Greek distinguishes between structural units (onoma/rhema paralleling pada), authoritative discourse (logos resembling vacana), and performative speech acts (epos/mythos echoing ākhyāta). The philosophical weight of logos particularly mirrors vāc’s cosmic dimensions, while lexis captures stylistic nuances absent in other traditions.</p>
<p>####Classical Arabic: Theological Sophistication</p>
<p>Arabic demonstrates comparable complexity through terms like kalām (speech, theology), qawl (saying, statement), lafẓ (pronunciation, verbal form), ḥarf (letter, particle), kalima (word), nuṭq (rational speech), and bayān (eloquent expression). The system shows striking parallels: ḥarf functions like akṣara as the atomic unit, kalima resembles pada as meaningful units, while kalām carries theological authority similar to vacana. Notably, nuṭq specifically denotes rational, articulate speech that distinguishes humans from animals, paralleling abhilāpa’s emphasis on conceptual construction.</p>
<p>####Classical Chinese: Contextual Stratification</p>
<p>Chinese exhibits a different but equally sophisticated pattern through characters like 言 (yán - speech, words), 語 (yǔ - language, discourse), 詞 (cí - word, expression), 字 (zì - character, written word), 聲 (shēng - sound, voice), 話 (huà - spoken words), and 辭 (cí - refined language, rhetoric). The system operates more contextually than morphologically: yán appears in formal, often written contexts; yǔ in conversational discourse; while cí (辭) specifically denotes elevated, literary expression. This contextual stratification parallels Sanskrit’s register distinctions but achieves them through different linguistic mechanisms.</p>
<p>####Latin: Institutional Authority</p>
<p>Latin’s system includes verbum (word), sermo (conversation, discourse), oratio (formal speech), dictum (saying, pronouncement), vox (voice), lingua (tongue, language), and eloquium (eloquent speech). The pattern emphasizes institutional and social authority: oratio denotes formal, public speech; sermo indicates informal discourse; dictum carries authoritative weight similar to ākhyāta. The distinction between verbum (semantic unit) and vox (phonetic reality) parallels the pada/akṣara relationship in Sanskrit.</p>
<p>####Hebrew: Sacred and Profane Dimensions</p>
<p>Biblical and Rabbinic Hebrew shows דבר (davar - word, thing, matter), אמר (amar - saying), מלה (milla - word), קול (qol - voice, sound), לשון (lashon - tongue, language), שיח (siach - speech, meditation), and הגה (haga - utterance, meditation). Uniquely, davar means both “word” and “thing,” suggesting deep ontological connections between language and reality that parallel prajñapti’s conventional establishment function. The sacred/profane distinction appears through terms like haga, used for both speech and religious meditation.</p>
<p>####German: Conceptual Precision</p>
<p>Modern German exhibits systematic near-synonymy through Wort (word), Sprache (language), Rede (speech, discourse), Aussage (statement), Äußerung (utterance), Ausdruck (expression), and Bezeichnung (designation). German’s compound-forming capacity creates precise distinctions: Bezeichnung specifically denotes the act of linguistic designation (paralleling prajñapti), while Äußerung emphasizes the externalization of internal states. The philosophical tradition from Herder through Heidegger has developed these distinctions with remarkable precision.</p>
<p>####Japanese: Honorific Stratification</p>
<p>Japanese demonstrates complexity through 言葉 (kotoba - words, language), 語 (go - word, language), 話 (hanashi - talk, story), 声 (koe - voice), 発言 (hatsugen - statement), 表現 (hyōgen - expression), and 言語 (gengo - language system). The system integrates honorific levels: different terms apply depending on social relationships and formality levels. This social stratification of near-synonyms, while different from Sanskrit’s philosophical distinctions, shows how languages can systematically organize semantic fields according to cultural priorities.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">frequency</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">by genre</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-3" role="tab" aria-controls="tabset-6-3" aria-selected="false">% by genre</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-4" role="tab" aria-controls="tabset-6-4" aria-selected="false">table</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangAsVerbalExpression.webp" class="img-fluid figure-img" alt="abhilāpa=272;ākhyāta=402;akṣara=558;pada=479;prajñapti=142;vāc=3900;vacana=3592"></p>
<figcaption class="figure-caption">Language as verbal expression, absolute freq</figcaption>
</figure>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<p><img src="www/LangAsVerbalExpressionByGenre.webp" class="img-fluid" alt="Language as verbal expression, absolute freq by genre"> ### % by genre</p>
</div>
<div id="tabset-6-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-3-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangAsVerbalExpressionPercByGenre.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Language as verbal expression, percentage by genre</figcaption>
</figure>
</div>
</div>
<div id="tabset-6-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-4-tab">
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>frequency of words meaning verbal expression, by genre</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">lemma</th>
<th style="text-align: center;">avadāna</th>
<th style="text-align: center;">dhāraṇī</th>
<th style="text-align: center;">lit</th>
<th style="text-align: center;">other</th>
<th style="text-align: center;">sādhana</th>
<th style="text-align: center;">śāstra</th>
<th style="text-align: center;">stotra</th>
<th style="text-align: center;">sūtra</th>
<th style="text-align: center;">tantra</th>
<th style="text-align: center;">vinaya</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">abhilāpa</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">226</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">ākhyāta</td>
<td style="text-align: center;">64</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">142</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">20</td>
</tr>
<tr class="odd">
<td style="text-align: center;">akṣara</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">159</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">152</td>
<td style="text-align: center;">144</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">pada</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">277</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">141</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">16</td>
</tr>
<tr class="odd">
<td style="text-align: center;">prajñapti</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">58</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">63</td>
</tr>
<tr class="even">
<td style="text-align: center;">vāc</td>
<td style="text-align: center;">233</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">267</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">106</td>
<td style="text-align: center;">1,370</td>
<td style="text-align: center;">62</td>
<td style="text-align: center;">897</td>
<td style="text-align: center;">762</td>
<td style="text-align: center;">175</td>
</tr>
<tr class="odd">
<td style="text-align: center;">vacana</td>
<td style="text-align: center;">363</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">148</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">2,656</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">242</td>
<td style="text-align: center;">103</td>
<td style="text-align: center;">27</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-conceptualization" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="sec-conceptualization"><span class="header-section-number">1.4</span> Language as conceptualization</h2>
<p>The link between language and the conceptual construction of experience is a central theme in Buddhism. Two words articulate the interface between linguistic labels and notions, their conceptual counterpart: <strong><em>saṃjñā</em></strong> and <strong><em>prajñapti</em></strong>. Both words are polysemic and express several semantic nuances in the domain of language, but both words’ connection with language hinges precisely on their role in bridging vocabulary and concepts. They do so from two different angles. Saṃjñā, as its overall semantic spectrum suggests, captures the cognitive process that goes from perception to verbal labelling. Prajñapti, as the etymology suggests, does the reverse and ‘makes known’ concepts through verbal articulation. Since the meaning of these words is a blend of linguistic and cognitive processing of experience, it is often difficult, especially in the case of saṃjñā, to differentiate cases where these words point to language as conceptualization from cases where their meaning is wider. Hence we refrain from plotting the distribution of these words in this sense, as it may provide a misleadingly neat picture.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">near-synonym analysis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Parallel patterns of near-synonymy in other languages</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<p><strong><em>Saṃjñā</em></strong> often appears in compound formations that describe specific types of linguistically mediated notions or mental images, such as <em>puruṣa-saṃjñā</em> (<em>Pañcakrama</em>, 103: the notion of man) or <em>śmaśāna-saṃjñā</em> (<em>Mahāvastu</em>, 16955: the idea of a cemetery). Collocation with verbs of arising such as ut√pad indicates that <em>saṃjñā</em> is associated to a spontaneous mental categorization that arises in response to particular stimuli or situations, as in <em>Mahāvastu</em>, 12423: “<em>śāriputrasya taṃ jana-kāyaṃ dṛṣṭvā a-nitya-saṃjñā utpannā</em>” (“For when Śāriputra saw that great crowd of people there arose in him the awareness of the impermanence of things.” [Jones III 59]) or <em>Vajracchedikā,</em> 10: “<em>āścaryeṇa samanvāgatā bhaviṣyaṃti ya iha sūtre bhāṣyamāṇe bhūtasaṃjñām utpādayiṣyaṃti / yā caiṣā bhagavan / bhūtasaṃjñā saivāsaṃjñā tasmāt tathāgato bhāṣate bhūtasaṃjñā bhūtasaṃjñeti /</em>” (“They will come to be endowed with a most marvelous thing, Lord, who when this discourse is being preached conceive the idea that it is the truth. But any such idea of truth, Lord, is indeed idealess. Therefore the Realized One preaches the so-called ‘idea of truth.’” [Harrison 149]). However saṃjñā also encompasses abstract categorizations, typically those that one should overcome, which gives saṃjñā in this sense a rather negative connotation, as in <em>Vajracchedikā</em>, 17 “<em>na satva-saṃjñā na jīva-saṃjñā na pudgala-saṃjñā</em>” (“… nor will the idea of a living being, the idea of a soul, or the idea of a person occur.” [Harrison]) or <em>Vimalakīrtinirdeśa,</em> 2357: “<em>na mārga-saṃjñā bhavati na kumārga-saṃjñā</em>” (“… does not entertain any notions of a right path or a wrong path, …” [Gómez and Harrison 99]), or <em>Samādhirāja</em>, 744: “<em>saṃjñā prahīṇa sarvā niravaśeṣā</em>” (“All notions have been completely abandoned.” [machine-translated with Dharmamitra]).</p>
<p><strong><em>Prajñapti</em></strong> by contrast has a less negative connotation. Its emphasis is more ontological than cognitive, appearing often in philosophical discourse about the superimposition of designation onto fundamentally unreal entities, with the topos of attaching the label ‘self’ to the five aggregates (see section on Language as construct), as in <em>Abhidharmakośabhāṣya</em>, 13761: “<em>nahi te skandha-saṃtāna ev ātma-prajñaptiṃ vyavasyanti /</em>” (“How do we know that the word ‘soul’ is only a designation for a series of <em>skandhas</em>, and that no soul exists in and of itself?” [Pruden 1313]), or <em>Sphuṭārtha_abhidharmakośavyākhyā</em>, 36741: “t<em>eṣv eva skaṃdheṣu pudgala-prajñaptiḥ prāpnoti</em>” (“The designation of a person (pudgala) arises precisely in these aggregates (skaṃdha).” [machine-translated with Dharmamitra]), or <em>Satyasiddhiśāstra</em>, 2903: “<em>pañca-skandhānāṃ kalāpaḥ prajñaptyā ātm^eti</em>” (“The self [ātman] is a collection of the five aggregates existing nominally.” [machine-translated with Dharmamitra]). This labelling is rarely characterised as erroneous. Prajñapti is typically depicted as a ‘mere’ designation, not a wrong one: “<em>prajñapti-mātrā tribhavaṃ nāsti vastu svabhāvataḥ”</em> [<em>Laṅkāvatārasūtra</em>, 2741] (”52. The triple world is no more than thought-construction (prajñapti), there is no reality in its self-nature; …” [Suzuki]); “<em>cakṣur-vijñānaṃ kauśika prajñapti-mātraṃ yat prajñapti-mātraṃ sā dharmatā</em>” [<em>Śatasāhasrikāprajñāpāramitā</em>, 61237] (“O Kauśika, visual consciousness is merely a designation. That which is merely a designation is the ultimate reality.” [machine-translated with Dharmamitra]).</p>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<p><code>CAUTION: the following content is AI-generated with Claude Sonnet 4 and has not been reviewed.</code></p>
<section id="indo-european-languages" class="level4" data-number="1.4.0.1">
<h4 data-number="1.4.0.1" class="anchored" data-anchor-id="indo-european-languages"><span class="header-section-number">1.4.0.1</span> Indo-European Languages</h4>
<p><strong>Greek</strong> displays a parallel distinction in philosophical contexts:</p>
<ul>
<li><strong>νόησις (noesis)</strong>&nbsp;- immediate intellectual apprehension, direct cognitive grasp</li>
<li><strong>διάνοια (dianoia)</strong>&nbsp;- discursive thinking, conceptual reasoning through language</li>
</ul>
<p>This mirrors the saṃjñā/prajñapti distinction, with noesis representing direct cognitive recognition and dianoia representing the conventional, step-by-step conceptual process.</p>
<p><strong>German</strong> philosophical terminology shows:</p>
<ul>
<li><strong>Anschauung</strong>&nbsp;- immediate intuitive perception/cognition</li>
<li><strong>Begriff</strong>&nbsp;- concept formed through social-linguistic convention Kant’s distinction between these terms parallels the Buddhist dyad, where Anschauung captures immediate cognitive apprehension while Begriff represents socially constructed conceptual categories.</li>
</ul>
<p><strong>French</strong> exhibits:</p>
<ul>
<li><strong>aperception</strong>&nbsp;- immediate conscious recognition</li>
<li><strong>conception</strong>&nbsp;- conventional conceptual formation This appears in phenomenological contexts where aperception denotes direct cognitive awareness while conception involves linguistic-cultural construction.</li>
</ul>
</section>
<section id="east-asian-languages" class="level4" data-number="1.4.0.2">
<h4 data-number="1.4.0.2" class="anchored" data-anchor-id="east-asian-languages"><span class="header-section-number">1.4.0.2</span> East Asian Languages</h4>
<p><strong>Chinese</strong> philosophical vocabulary demonstrates:</p>
<ul>
<li><strong>知 (zhī)</strong>&nbsp;- direct knowing/recognition</li>
<li><strong>名 (míng)</strong>&nbsp;- naming/conventional designation This distinction appears prominently in Daoist texts, where zhī represents immediate cognitive awareness while míng represents the conventional linguistic categories that potentially obscure direct understanding.</li>
</ul>
<p><strong>Japanese</strong> shows:</p>
<ul>
<li><strong>知覚 (chikaku)</strong>&nbsp;- direct perception/cognition</li>
<li><strong>概念 (gainen)</strong>&nbsp;- conventional concept In Buddhist contexts, chikaku often translates saṃjñā while gainen corresponds to prajñapti-like conventional designations.</li>
</ul>
</section>
<section id="semitic-languages" class="level4" data-number="1.4.0.3">
<h4 data-number="1.4.0.3" class="anchored" data-anchor-id="semitic-languages"><span class="header-section-number">1.4.0.3</span> Semitic Languages</h4>
<p><strong>Arabic</strong> philosophical terminology displays:</p>
<ul>
<li><strong>إدراك (idrāk)</strong>&nbsp;- immediate cognitive apprehension</li>
<li><strong>مفهوم (mafhūm)</strong>&nbsp;- conventional concept/understanding This appears in Islamic philosophical texts where idrāk represents direct cognitive grasp while mafhūm involves linguistically mediated conceptual construction.</li>
</ul>
<p><strong>Hebrew</strong> shows:</p>
<ul>
<li><strong>השגה (hasagah)</strong>&nbsp;- direct cognitive attainment</li>
<li><strong>מושג (musag)</strong>&nbsp;- conventional concept This distinction appears in medieval Jewish philosophy, particularly in discussions of divine knowledge versus human conceptual categories.</li>
</ul>
</section>
<section id="finno-ugric-languages" class="level4" data-number="1.4.0.4">
<h4 data-number="1.4.0.4" class="anchored" data-anchor-id="finno-ugric-languages"><span class="header-section-number">1.4.0.4</span> Finno-Ugric Languages</h4>
<p><strong>Finnish</strong> exhibits:</p>
<ul>
<li><strong>tiedostaminen</strong>&nbsp;- direct conscious awareness</li>
<li><strong>käsitteellistäminen</strong>&nbsp;- conceptualization through language The first emphasizes immediate cognitive recognition while the second involves conventional linguistic categorization.</li>
</ul>
</section>
<section id="niger-congo-languages" class="level4" data-number="1.4.0.5">
<h4 data-number="1.4.0.5" class="anchored" data-anchor-id="niger-congo-languages"><span class="header-section-number">1.4.0.5</span> Niger-Congo Languages</h4>
<p><strong>Yoruba</strong> demonstrates:</p>
<ul>
<li><strong>mọ̀</strong>&nbsp;- direct knowing/recognition</li>
<li><strong>orúkọ</strong>&nbsp;- naming/conventional designation This appears in traditional epistemological contexts where mọ̀ represents immediate cognitive awareness while orúkọ involves social-linguistic designation.</li>
</ul>
</section>
<section id="austronesian-languages" class="level4" data-number="1.4.0.6">
<h4 data-number="1.4.0.6" class="anchored" data-anchor-id="austronesian-languages"><span class="header-section-number">1.4.0.6</span> Austronesian Languages</h4>
<p><strong>Indonesian/Malay</strong> shows:</p>
<ul>
<li><strong>kesadaran</strong>&nbsp;- direct awareness/consciousness</li>
<li><strong>pengertian</strong>&nbsp;- conventional understanding/concept The distinction appears in philosophical translations where kesadaran captures immediate cognitive recognition while pengertian involves linguistically mediated understanding.s</li>
</ul>
</section>
</div>
</div>
</div>
</section>
<section id="sec-construct" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="sec-construct"><span class="header-section-number">1.5</span> Language as construct</h2>
<p>Much of the Buddhist philosophical treatment of Language focuses on the idea that language is an artificial construct we use to approximatively talk about phenomena, but ultimately has no ontological foundation and no real link to those phenomena. This is a topic instantiated almost exclusively in sūtra and śātras, so the following analysis will zoom in on these two text types only. The principal vocabulary used to convey this aspect of language as construct consists of <strong><em>prajñapti</em></strong>, <strong><em>vyavahāra</em></strong>, <strong><em>saṃketa</em></strong> and <strong><em>upacāra</em></strong>. While they all express the idea that language is but an artificial approximation of reality, only vyavahāra and saṃketa can be taken as near-synonyms, as they both stress the socially agreed, or conventional, dimension of language. Prajñapti, by contrast, foregrounds the ontological aspect of language as a conceptual construct that lacks a real foundation. Finally, upacāra highlights the metaphorical, non-literal, aspect of communication, whereby unreal phenomena can be named in a manner of speaking, without implying their existence. Interestingly, the ontological aspect lexicalized by <em>prajñāpti</em> is widespread in earlier layers of the corpus, where it features prominently in prajñāpāramitā sūtras, abhidharma and philosophical treatises, but steadily declines overtime, being replaced by words foregrounding the socially agreed aspect of language, with <em>vyavahāra</em> and, to a lesser extent, <em>saṃketa</em> dominating the lexical field of language as construct in <em>pramāṇa</em> literature of later periods. The inverse correlation between language as conceptualization and language as construction in the plot below evidences the diachronic shift in emphasis from language as conceptual construct devoid of an ontological basis towards an understanding of language as a social construct based on consensus.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true">lexical analysis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false">Parallel patterns of near-synonymy in other languages</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<p><strong>Prajñapti</strong>, together with <em>vyavahāra</em>, are the most prototypical words that lexicalize this aspect of language. Prajñapti emphasises the cognitive and ontological dimension of this domain, conveying the idea of words as conceptual constructs superimposed on ultimately unreal phenomena. The frequent collocation prajñapti-sat features prominently in <code>abhidharma</code> and <code>philosophical texts</code>, where it is typically contrasted with dravya-sat and, at times, paramārtha-sat, as in <em>Laṅkāvatārasūtra</em>,&nbsp;62: “<em>prajñapti-satyato hy ātmā dravya-san na hi vidyate / skandhānāṃ skandhatā tadvat prajñaptyā na tu dravyataḥ //</em>” (“An ego-soul is a truth belonging to thought-construction, in which there is no real reality; the self-nature of the Skandhas is also a thought-construction, as there is no reality in it.” [Suzuki 132]), or <em>Satyasiddhiśāstra</em>, 12919: “<em>yogī pūrvaṃ dharmāḥ kiṃ prajñapti-santaḥ kiṃ vā paramārtha-santa iti jñātvā …</em>” (“The yogi, having first known whether phenomena are conventionally existent or ultimately real, …” [machine-translated with Dharmamitra]).</p>
<p><strong>Vyavahāra</strong> is the most prominent word expressing the idea that language is a social convention. This sense constitutes the very core of <a href="https://mangalamresearch-lexicography.github.io/LexicalPortraits/vyavahAra.html" title="vyavahāra Lexical Portrait"><em>vyavahāra</em> semantic spectrum</a><a href="https://mangalamresearch-lexicography.github.io/LexicalPortraits/vyavahAra.html">,</a> which makes this word the prototypical choice for expressing the practical utility of language despite its limitations, as in <em>Vigrahavyāvartanī</em>, 262:“<em>vyavahāram anāśritya paramārtho na deśyate /</em>” (“Not having had recourse to the conventional, the absolute is not taught.” [Westerhoff 29]), or <em>Abhisamayālaṃkārāloka</em>, 11370: “<em>sarva-dharmāś ca nāmamātreṇa vyavahāra-mātreṇ ābhilapyanta iti</em>” (“All phenomena are designated merely by names and conventions.” [machine-translated with Dharmamitra]).</p>
<p><strong>Saṃketa</strong> emphasizes the arbitrary yet systematic nature of linguistic convention and the role of mutual agreement in establishing meaning. It refers specifically to conventional signs and agreed-upon meanings. Later literature uses this word to clarify the mechanics of how semantic relationships are established, as in <em>Pramāṇavārttikālaṅkārabhāṣya</em>, 10522: “<em>tasmāt saṃketa-kāle pi nir-dṛṣṭ-^ārthena saṃyutaḥ</em>” (“Therefore, even at the time of convention, [a word] is conjoined with a designated object.” [machine-translated with Dharmamitra]) and <em>Pramāṇavārttikālaṅkārabhāṣya</em>, 10333: “<em>saṅketa-anvayinī rūḍhir vaktur icchā-anvayī ca saḥ</em>” (“Conventional usage is connected to a signal, and it is also connected to the speaker’s intention.” [machine-translated with Dharmamitra]). In earlier period and <code>sūtra</code> literature the connection with arbitrary decisions is less explicit but still present, as in <em>Samādhirāja</em>,&nbsp;299: “<em>katamaḥ nāma-saṃketaḥ / yad idaṃ a-pariniṣpannānāṃ nāmnām anubudhyanatā //</em>”&nbsp;(“What is the knowledge of assigned names? It is the understanding that names are without reality.” [Roberts/84000 40.66]).</p>
<p><strong>Upacāra</strong> lies at the margin of these lexical field, as it expresses a more deliberate form of linguistic construction than the words we have previously analysed. It denotes the non-literal aspect of verbal expression, whereby things are meant by figure of speech, especially metonymy, such as designating the effect by the cause, or applying collective terms to individual parts, as in <em>Abhidharmakośabhāṣya</em>,&nbsp;10128: “<em>prahāṇa-parijñā tu prahāṇam eva / phale het-^ūpacārāt /”</em>&nbsp;(”‘perfect knowledge which produces abandoning,’ which is abandoning itself, for the effect is designated by the name of its cause.” [Pruden 859]) or <em>Hetubinduṭīkā</em>, 219: “<em>avayave samudāy^opacārāt</em>” (“Due to the figurative use of ‘whole’ for a ‘part.’” [machine-translated with Dharmamitra]).</p>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<section id="german-philosophical-terminology" class="level4" data-number="1.5.0.1">
<h4 data-number="1.5.0.1" class="anchored" data-anchor-id="german-philosophical-terminology"><span class="header-section-number">1.5.0.1</span> German Philosophical Terminology</h4>
<p>German has perhaps the most developed set of terms, particularly through phenomenology and hermeneutics:</p>
<p>Konstruktion - deliberate cognitive construction Konstitution - phenomenological constitution of meaning Setzung - positing or stipulation (Husserlian) Vereinbarung - conventional agreement Sprachspiel - language game (Wittgensteinian) Verständigung - mutual understanding/communication These terms emerged from German idealism and phenomenology, creating nuanced distinctions between different modes of meaning-construction.</p>
</section>
<section id="french-post-structuralist-vocabulary" class="level4" data-number="1.5.0.2">
<h4 data-number="1.5.0.2" class="anchored" data-anchor-id="french-post-structuralist-vocabulary"><span class="header-section-number">1.5.0.2</span> French Post-Structuralist Vocabulary</h4>
<p>French developed a rich terminology through structuralism and post-structuralism:</p>
<p>Convention - social convention Construction - cognitive/social construction Stipulation - arbitrary stipulation Signification - meaning-making process Énonciation - the act of enunciation (vs.&nbsp;énoncé - the statement) Discours - discourse as constructed practice</p>
</section>
<section id="classical-chinese-philosophical-terms" class="level4" data-number="1.5.0.3">
<h4 data-number="1.5.0.3" class="anchored" data-anchor-id="classical-chinese-philosophical-terms"><span class="header-section-number">1.5.0.3</span> Classical Chinese Philosophical Terms</h4>
<p>Chinese philosophy, particularly in discussions of language and reality, developed several key terms:</p>
<p>名 (míng) - names/designations 約定 (yuēdìng) - conventional agreement 假名 (jiǎmíng) - provisional/false names 施設 (shīshè) - conventional establishment 言說 (yánshuō) - verbal expression/discourse Notably, 施設 (shīshè) is actually the Chinese translation of Sanskrit prajñapti, showing direct conceptual borrowing.</p>
</section>
<section id="ancient-greek-philosophical-terminology" class="level4" data-number="1.5.0.4">
<h4 data-number="1.5.0.4" class="anchored" data-anchor-id="ancient-greek-philosophical-terminology"><span class="header-section-number">1.5.0.4</span> Ancient Greek Philosophical Terminology</h4>
<p>Greek philosophy established foundational distinctions:</p>
<p>Νόμος (nomos) - convention (vs.&nbsp;φύσις/physis - nature) Σύνθημα (synthema) - agreed sign/token Θέσις (thesis) - stipulation/positioning Συνθήκη (syntheke) - compact/agreement Διάλεκτος (dialektos) - discourse/dialect Modern English Academic Clusters English has developed several overlapping terminological clusters:</p>
<p>Cognitive Science: conceptualization, categorization, construal, framing Sociology: social construction, convention, discourse, practice Philosophy of Language: stipulation, designation, reference-fixing, semantic agreement</p>
</section>
<section id="significant-patterns" class="level4" data-number="1.5.0.5">
<h4 data-number="1.5.0.5" class="anchored" data-anchor-id="significant-patterns"><span class="header-section-number">1.5.0.5</span> Significant Patterns</h4>
<p>Deliberate vs.&nbsp;Emergent Construction - Most languages distinguish between conscious stipulation and unconscious social emergence Individual vs.&nbsp;Social - Terms often differentiate cognitive construction from social agreement Temporary vs.&nbsp;Stable - Many languages mark whether constructions are provisional or established Metaphorical vs.&nbsp;Literal - Recognition of extended vs.&nbsp;primary usage</p>
</section>
</div>
</div>
</div>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangAsConstruct.webp" class="img-fluid figure-img" alt="prajñapti=842;saṃketa=882;upacāra=449;vyavahāra=2120"></p>
<figcaption class="figure-caption">frequency of each lemma in the field of language as construct</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/DiachLangInSutraAndSastra.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">diachronic distribution of various aspects of Language in scriptures (sūtras+tantras) and śāstras in our corpus</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangAsConstructByPeriod.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">diachronic distribution of words expressing language as construct in scriptures (sūtra+tantra+dhāraṇī) and śāstras in our corpus, as percentage</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/LangAsConstructByPeriod_AbsFreqs.webp" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">diachronic distribution of words expressing language as construct in scriptures (sūtra+tantra) and śāstras in our corpus, absolute frequencies</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="sec-sound" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="sec-sound"><span class="header-section-number">1.6</span> Language as sound</h2>
<p>Three near synonyms express the concept of language as sound in our corpus, <strong><em>ghoṣa</em></strong>, <strong><em>ruta</em></strong>, and <strong><em>śabda</em></strong>. <em>Ghoṣa</em> is perhaps the most prototypical word to convey this aspect of language, as this specific meaning is central to its semantic spectrum (see <a href="https://mangalamresearch-lexicography.github.io/LexicalPortraits/ghoSa.html" title="ghoṣa">our ghoṣa lexical portrait</a>).</p>
<p>While the overall meaning of these words in the sense of verbal sound is similar, each carries unique contextual and connotational qualities.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true">near-synonyms analysis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false">Parallel patterns of near-synonymy in other languages</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<p><strong>Ghoṣa</strong> emerges as perhaps the most spiritually charged term among the three. It frequently appears in contexts describing divine or transcendent vocal expressions, particularly those associated with the Buddha and other enlightened beings. An example is <em>Bauddhastotrasaṃgraha</em>, 1157: “<em>sarva-sur-^āsurasu svara-ghoṣaṃ brahma-ruta-svara-garjita-ghoṣam</em>”, where <em>ghoṣa</em> is explicitly linked to divine sound that resonates across celestial realms. The term consistently appears in descriptions of proclamations that carry profound spiritual significance, as in the <em>Saddharmapuṇḍarīka</em>, 1335 where “<em>ghoṣam anuśrāvayati</em>” describes the transmission of the Dharma. A typical but semantically illuminating use is the scholastic explanations of <em>ghoṣa</em> as meaningful sound in the context of language, as in <em>Abhidharmakośabhāṣya</em>, 2723: “<em>vāṅ-nāmni pravrttate nām-^ārthaṃ dyotayati n ^aiva ghoṣa-mātraṃ vāg yena tu ghoṣeṇ ^ārthaḥ pratīyate sa ghoṣo vāk /</em>” (“They are not ‘voice.’ Voice is ‘vocal sound,’ and a vocal sound only; for example, a cry does not cause one to attain to or comprehend an object. But a word <em>(nāman)</em> which moreover is a function of vocal sound, illumines, causes one to attain to, or signifies the object.” [Pruden 251]).</p>
<p><strong>Ruta</strong>, by contrast, carries a more melodious and aesthetically refined quality. The term appears frequently in poetic contexts where the beauty and harmony of sound are emphasized. For example, <em>Ratnagotravibhāga,</em> 1476: “<em>surendraratnapratibhāsadarśanaḥ sudaiśiko dundubhivad vibho rutam | vibhur mahājñānakṛpābhramaṇḍalaḥ spharaty anantaṃ jagad ā bhavāgrataḥ</em>” (“The excellent teacher has an appearance Like the reflection of the chief of gods on the jewel, His voice is like the [sound of] the divine drum, Having the great sphere of the clouds of Wisdom and Mercy, He pervades an unlimited number of living beings, Up to the highest limit of existence.” [Takasaki 376]), where <em>ruta</em> is associated with the magnificent sound of celestial drums, emphasizing its musical and rhythmic qualities. The word often appears in descriptions of voices that are not merely heard but appreciated for their tonal beauty, such as <em>Mahāvastu</em>, 9335: “<em>so maṃjughoṣo ruta-valgu-bhāṣī …</em>” (“The Bodhisattva …uttered this consummate speech in his entrancing and sweet-sounding voice.” [Jones II 301]), where <em>ruta</em> modifies speech that is specifically characterized as sweet and melodious. This suggests that <em>ruta</em> encompasses not just the acoustic properties of sound but its aesthetic and emotional impact on listeners. Unlike the other near-synonyms in this area, ruta rarely appears in contexts of mere announcement, instead gravitating toward descriptions of naturally beautiful or divinely pleasant sounds.</p>
<p><strong>Śabda</strong> demonstrates the broadest semantic range and appears to function as the most neutral and comprehensive term for sound and speech. It encompasses everything from ordinary human communication to divine proclamations, but without the specialized connotations of its counterparts. Sentences like <em>Saddharmapuṇḍarīka</em>, 1334: “sa-deva-mānuṣ-^āsurasya lokasya purata evaṃ śabdam udīrayati” (“… the Tathāgata, the Arhat, &amp;c., before the face of the world, including gods, men, and demons, lifts his voice …” [Kern 120]) show <em>śabda</em> describing the Buddha’s teaching voice addressing all realms of existence, but the focus is on communicative function rather than spiritual quality. <em>Śabda</em> appears frequently in narrative contexts describing various types of sounds, from the distressing cries in <em>Divyāvadāna</em>, 16160: “<em>tatra tāni pañca-mātrāṇi māṇavaka-śatāni uccaiḥ śabdāni procur mahā śabdāni</em>” (“There, those five hundred young Brahman students loudly uttered many sounds.” [machine-translated with Dharmamitra]) to voices emerging from space in <em>Dvāviṃśatyavadānakathā</em>, 1792: “<em>tata ākāśāc chabdo niścārita</em> …” (“Then, a sound emanated from the sky.” [machine-translated with Dharmamitra]).</p>
<p>The contextual differences become even more apparent when examining how these terms interact with their surrounding vocabulary. <em>Ghoṣa</em> frequently collocates with words related to spiritual realization and divine presence, often appearing alongside words like <em>buddha</em>, <em>dharma</em>, and <em>vajra</em>. <em>Ruta</em> tends to appear with aesthetic qualifiers and in descriptions of pleasing or harmonious sounds, often modified by words suggesting beauty or melodiousness. <em>Śabda</em>, meanwhile, appears in the widest variety of contexts, from mundane announcements to cosmic proclamations, suggesting its role as the unmarked term in this semantic field.</p>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<p><code>CAUTION: the following content is AI-generated with Claude Sonnet 4 and has not been reviewed.</code></p>
<p>Several languages exhibit similar fine-grained distinctions for the auditory aspects of language, though perhaps none quite as systematically as Sanskrit.</p>
<p><strong>Classical Greek</strong> offers a particularly rich parallel. The language distinguishes between <em>phōnē</em> (φωνή), <em>logos</em> (λόγος), and <em>rhēma</em> (ῥῆμα) in ways that echo your Sanskrit triad. <em>Phōnē</em> refers to voice or sound in its physical manifestation, <em>logos</em> encompasses reasoned speech with philosophical or divine connotations (think of the opening of John’s Gospel: “In the beginning was the <em>logos</em>”), and <em>rhēma</em> focuses on the utterance as a unit of meaning. Greek also has <em>ēchos</em> (ἦχος) for resonant sound, which appears in contexts describing oracular pronouncements or divine voices.</p>
<p><strong>Arabic</strong> presents another compelling case with <em>ṣawt</em> (صوت), <em>kalām</em> (كلام), and <em>qawl</em> (قول). <em>Ṣawt</em> is the general term for sound, <em>kalām</em> carries theological weight (it’s used for divine speech and is central to Islamic theology), while <em>qawl</em> refers to human utterance or saying. The Quran’s own self-reference as <em>kalām Allāh</em> (the speech of God) shows how these distinctions carry profound religious significance.</p>
<p><strong>Japanese</strong> offers interesting parallels with <em>koe</em> (声) for voice, <em>oto</em> (音) for sound, and <em>kotoba</em> (言葉) for words/language. But perhaps more intriguingly, Japanese has <em>hibiki</em> (響き) for resonance or reverberation, which often appears in aesthetic contexts much like Sanskrit <em>ruta</em>.</p>
<p><strong>Classical Chinese</strong> distinguishes between <em>shēng</em> (聲) for voice/sound, <em>yīn</em> (音) for tone/musical sound, and <em>yán</em> (言) for speech/words. The philosophical tradition makes much of these distinctions, particularly in discussions of music theory and the relationship between sound and meaning.</p>
<p>The <strong>Germanic languages</strong>, including Old English, had similar tripartite systems: <em>stefn</em>/<em>stimme</em> for voice, <em>hlūd</em>/<em>laut</em> for loud sound, and <em>word</em>/<em>wort</em> for word/speech, though these distinctions have somewhat flattened in modern English.</p>
</div>
</div>
</div>
</section>
<section id="sec-literal" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="sec-literal"><span class="header-section-number">1.7</span> Language as literal</h2>
<p>Considerable attention is given in Buddhist literature to the literal dimension of language, that is language as a set of signs as opposed to what they signify. Two main words lexicalize this aspect of language: <strong><em>ruta</em></strong> and <strong><em>vyañjana</em></strong>. While both are associated with the <code>hermeneutic discourse</code> and the <code>Mahāyāna</code> opposition between words and meanings, these two vocables are not synonyms.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true">lexical analysis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false">Parallel patterns of near-synonymy in other languages</a></li></ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<p><strong><em>Ruta</em></strong> typically expresses the idea of literality in the construction <em>yathā-ruta</em>, which circumscribes the wider sense of <em>ruta</em> as the audible aspect of words, which may evoke the idea of textual recitation and oral memorization of teachings. In this sense, <em>ruta</em> tends to acquire a negative connotation as the literal knowledge of the words and the teachings, often contrasted with the understanding of their meaning. In our corpus, the negative connotation of <em>ruta</em> as the literal aspect of words is amplified by its over-representation in a single text, the <em>Laṅkāvatārasūtra</em>, where ruta is consistently identified as soteriologically problematic, e.g.&nbsp;<em>Laṅkāvatārasūtra</em>, 3266: “<em>rutaṃ vikalpa-saṃbaddhaṃ saṃsār-^āvāhakam /</em>” (“Words are bound up with discrimination and are the carrier of transmigration.” [Suzuki 169).</p>
<p><strong>Vyañjana</strong> denotes letters or syllables, the building blocks of verbal expressions. Together with <em>nāman</em> and <em>pada</em> it makes up language, according to the traditional categorization <em>nāma-pada-vyañjana-kāya</em>.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> Yet, while <em>nāman</em> and <em>pada</em> tend to be discussed for their semantic properties and association with word-referents, <em>vyañjana</em>, like <em>ruta</em>, is typically contrasted with meaning and considered for its formal rather than semantic value. This lends vyañjana a negative connotation in contexts where the gap between mere words and the inexpressible reality is emphasised, as in <em>Laṅkāvatārasūtra</em>, 3236: “<em>artha-pratiśaraṇena mahāmate bodhisattvena mahāsattvena bhavitavyaṃ na&nbsp;vyañjana-pratiśaraṇena /</em>”&nbsp;(“Therefore, Mahāmati, let the Bodhisattva-Mahāsattva be in conformity with the meaning and not with the letter.” [Suzuki 167-168]), but opens the possibility of positive characterization in contexts where the well-spoken statements are praised, typically in discussions of the importance of a pairing profound meaning with pleasingly-spoken words for preaching, as in the phrase <em>sv-arthaṃ su-vyañjanaṃ</em>”, e.g.&nbsp;<em>Lalitavistara,</em>&nbsp;74: “<em>sv-arthaṃ su-vyañjanaṃ&nbsp;kevalaṃ paripūrṇaṃ pariśuddhaṃ paryavadātaṃ brahmacaryaṃ sattvānāṃ saṃprakāśayiṣyati /</em>” (“He will share a teaching of pure conduct, […] It will be a teaching with excellent meaning and excellent words. It will be unique, perfect, pure, purifying, and consummate.” [Dahl et al./84000 7.96]).</p>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<p><code>CAUTION: the following content is AI-generated with Claude Sonnet 4 and has not been reviewed.</code></p>
<section id="arabic" class="level4" data-number="1.7.0.1">
<h4 data-number="1.7.0.1" class="anchored" data-anchor-id="arabic"><span class="header-section-number">1.7.0.1</span> Arabic</h4>
<p>Arabic offers multiple terms for language’s literal aspects: - <strong>ḥarf</strong> (حرف) - letter, character, particle - <strong>lafẓ</strong> (لفظ) - utterance, pronunciation, verbal expression - <strong>kalima</strong> (كلمة) - word as spoken unit - <strong>ṣawt</strong> (صوت) - sound, phonetic element These contrast with <strong>ma’nā</strong> (معنى) meaning “meaning” or “sense”</p>
</section>
<section id="hebrew" class="level4" data-number="1.7.0.2">
<h4 data-number="1.7.0.2" class="anchored" data-anchor-id="hebrew"><span class="header-section-number">1.7.0.2</span> Hebrew</h4>
<p>Hebrew distinguishes: - <strong>ʾot</strong> (אות) - letter, sign, character - <strong>millah</strong> (מילה) - word as unit - <strong>ṣurah</strong> (צורה) - form, shape (of language) - <strong>qol</strong> (קול) - voice, sound Versus <strong>mashmaʿut</strong> (משמעות) for “meaning”</p>
</section>
<section id="german" class="level4" data-number="1.7.0.3">
<h4 data-number="1.7.0.3" class="anchored" data-anchor-id="german"><span class="header-section-number">1.7.0.3</span> German</h4>
<p>German provides sophisticated distinctions: - <strong>Buchstabe</strong> - letter, character - <strong>Laut</strong> - sound, phoneme - <strong>Wortlaut</strong> - exact wording, literal text - <strong>Klang</strong> - sound quality, resonance - <strong>Schrift</strong> - writing, script Contrasted with <strong>Bedeutung</strong> (meaning) and <strong>Sinn</strong> (sense)</p>
</section>
<section id="chinese" class="level4" data-number="1.7.0.4">
<h4 data-number="1.7.0.4" class="anchored" data-anchor-id="chinese"><span class="header-section-number">1.7.0.4</span> Chinese</h4>
<p>Classical and modern Chinese offer: - <strong>字</strong> (zì) - character, written form - <strong>音</strong> (yīn) - sound, pronunciation - <strong>聲</strong> (shēng) - voice, tone - <strong>文</strong> (wén) - written language, script - <strong>詞</strong> (cí) - word as linguistic unit Distinguished from <strong>義</strong> (yì) or <strong>意</strong> (yì) for meaning</p>
</section>
<section id="japanese" class="level4" data-number="1.7.0.5">
<h4 data-number="1.7.0.5" class="anchored" data-anchor-id="japanese"><span class="header-section-number">1.7.0.5</span> Japanese</h4>
<p>Japanese inherited and developed: - <strong>文字</strong> (moji) - letter, character - <strong>音</strong> (on) - sound, pronunciation - <strong>声</strong> (koe) - voice - <strong>語</strong> (go) - word as unit - <strong>字面</strong> (jimmen) - literal surface Versus <strong>意味</strong> (imi) for meaning</p>
</section>
<section id="greek" class="level4" data-number="1.7.0.6">
<h4 data-number="1.7.0.6" class="anchored" data-anchor-id="greek"><span class="header-section-number">1.7.0.6</span> Greek</h4>
<p>Ancient and modern Greek distinguish: - <strong>gramma</strong> (γράμμα) - letter, written mark - <strong>phōnē</strong> (φωνή) - voice, sound - <strong>lexis</strong> (λέξις) - word, diction - <strong>rhēma</strong> (ῥῆμα) - utterance, spoken word From <strong>logos</strong> (λόγος) or <strong>nous</strong> (νοῦς) for meaning/sense</p>
</section>
<section id="latin" class="level4" data-number="1.7.0.7">
<h4 data-number="1.7.0.7" class="anchored" data-anchor-id="latin"><span class="header-section-number">1.7.0.7</span> Latin</h4>
<p>Latin provides: - <strong>littera</strong> - letter, character - <strong>sonus</strong> - sound - <strong>vox</strong> - voice, utterance - <strong>verbum</strong> - word as spoken unit - <strong>scriptum</strong> - written form Contrasted with <strong>sensus</strong> or <strong>significatio</strong> for meaning</p>
</section>
<section id="persianfarsi" class="level4" data-number="1.7.0.8">
<h4 data-number="1.7.0.8" class="anchored" data-anchor-id="persianfarsi"><span class="header-section-number">1.7.0.8</span> Persian/Farsi</h4>
<p>Persian offers: - <strong>ḥarf</strong> (حرف) - letter (borrowed from Arabic) - <strong>āvāz</strong> (آواز) - voice, sound - <strong>kalame</strong> (کلمه) - word - <strong>neveshteh</strong> (نوشته) - written form Versus <strong>ma’nī</strong> (معنی) for meaning</p>
</section>
<section id="russian" class="level4" data-number="1.7.0.9">
<h4 data-number="1.7.0.9" class="anchored" data-anchor-id="russian"><span class="header-section-number">1.7.0.9</span> Russian</h4>
<p>Russian distinguishes: - <strong>bukva</strong> (буква) - letter - <strong>zvuk</strong> (звук) - sound - <strong>slovo</strong> (слово) - word as unit - <strong>proiznoshenie</strong> (произношение) - pronunciation From <strong>smysl</strong> (смысл) or <strong>znachenie</strong> (значение) for meaning</p>
</section>
<section id="turkish" class="level4" data-number="1.7.0.10">
<h4 data-number="1.7.0.10" class="anchored" data-anchor-id="turkish"><span class="header-section-number">1.7.0.10</span> Turkish</h4>
<p>Turkish provides: - <strong>harf</strong> - letter (from Arabic) - <strong>ses</strong> - sound, voice - <strong>söz</strong> - word, utterance - <strong>yazı</strong> - writing, script Versus <strong>anlam</strong> or <strong>mana</strong> for meaning</p>
</section>
<section id="interesting-patterns" class="level4" data-number="1.7.0.11">
<h4 data-number="1.7.0.11" class="anchored" data-anchor-id="interesting-patterns"><span class="header-section-number">1.7.0.11</span> Interesting Patterns</h4>
<p>Several patterns emerge across these languages:</p>
<ol type="1">
<li><p><strong>Sound vs.&nbsp;Script</strong>: Most languages distinguish auditory (sound/voice) from visual (letter/character) aspects of literal language.</p></li>
<li><p><strong>Unit Distinctions</strong>: Many languages differentiate between minimal units (letters/sounds) and larger units (words/utterances).</p></li>
<li><p><strong>Form vs.&nbsp;Substance</strong>: The literal/meaning distinction often parallels broader philosophical categories of form versus substance or appearance versus reality.</p></li>
</ol>
</section>
</div>
</div>
</div>
</section>
<section id="sec-nonVerbal" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="sec-nonVerbal"><span class="header-section-number">1.8</span> non-verbal language</h2>
<p>A discussion of aspects of language would not be complete without mention of non-verbal communication. This theme is not frequent in our corpus. When it is, two words are usually used to express it, <strong><em>saṃjñā</em></strong> and <em><strong>saṃketa</strong>.</em></p>
<p><strong><em>Saṃjñā</em></strong> appears frequently in contexts involving hand gestures (<em>hasta-saṃjñā</em>), as seen in multiple instances where people communicate through hand signals when verbal communication is impossible or inappropriate. For example, in <em>Āryaśūra_jātakamālā</em>, 3082 we see “<em>strī-jan-^ādhikṛtair bhaya-viṣāda-vyākulitair hasta-saṃjñābhir apasāryamāṇā …</em>” (“The eunuchs, who were likewise alarmed, affected with anxiety, and afflicted, made signs to them with their hands that they should withdraw, …” [Speyer 361]) or <em>Āryaśūra_jātakamālā,</em>&nbsp;3281: “<em>ath^ainam anye kṣut-tarṣa-śrama-dharma-duḥkh-^ātura-śarīrāḥ kṛt-^āñjalayaḥ sāśru-nayanāḥ samabhipraṇamy^ārtatayā hasta-saṃjñābhiḥ pānīyam ayācanta /</em>” (“Then some of them, who suffered intensely from the pain of hunger, thirst, fatigue, and heat, after bowing to him with folded hands and eyes wet with tears, in the manner of supplicants, asked him for water by means of signs with their hands.” [Speyer 393]).</p>
<p><strong><em>Saṃketa</em></strong>, in line with its overall meaning of agreed convention, can mean a signal or established gesture, especially with √kṛ, as in <em>Samādhirāja</em>, 239: “<em>akṣibhyāṃ c^ānena&nbsp;saṃketaḥ kṛtaḥ</em>” /&nbsp;(“The king thought, ‘This bhikṣu is looking at my queens with lust in his mind and he is winking at them’!” [Roberts/84000 36.68]). In some cases it may refer to established symbolic systems within religious practice, as in <em>Abhiṣekanirukti</em>, 14: “<em>tasmāt sarveṣu tantreṣu saṃketena ca mudrayā …</em>” (“Therefore, in all <em>tantra</em>s, by means of conventional signs and <em>mudrā</em>s …” [machine-translated with Dharmamitra]), where <em>saṃketa</em> refers to established symbolic systems within religious practice.</p>
</section>
<section id="documentation" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="documentation"><span class="header-section-number">1.9</span> Documentation</h2>
<p>This entry has been made following procedure outlined in the Preface methodology section. Specifically, this entry is based on 33,357 sentences taken from version v20 of our corpus (https://zenodo.org/records/17377159) and semantically tagged with Claude Sonnet 3.7. An evaluation of the accuracy of the tags for each word can be found in Lugli 2025.</p>
<section id="categorization" class="level3" data-number="1.9.1">
<h3 data-number="1.9.1" class="anchored" data-anchor-id="categorization"><span class="header-section-number">1.9.1</span> categorization</h3>
<section id="periodization" class="level4" data-number="1.9.1.1">
<h4 data-number="1.9.1.1" class="anchored" data-anchor-id="periodization"><span class="header-section-number">1.9.1.1</span> Periodization</h4>
<p>We follow here the periodization of our corpus Metadata, with some alteration.</p>
<p><strong>foundational</strong> period includes earlier texts up to about the end of the 3rd century CE</p>
<p><strong>classical</strong> includes texts likely composed around the 4th-5th century CE. Here we included texts with date_range = “5.-6. CE” and “4.-6. CE” in the corpus Metadata, whereas in the corpus Metadata those are categorizes as ‘commentarial’ and ‘uncertain’ respectively.</p>
<p><strong>early commentarial</strong> represents one of the two intervals into which we split the Metadata’s ‘commentarial’ period. Early commentarial includes texts likely dating from the 6th to the 8th century CE</p>
<p><strong>late commentarial</strong> includes texts from around the 9th up to about the 14th century CE.</p>
</section>
<section id="genres" class="level4" data-number="1.9.1.2">
<h4 data-number="1.9.1.2" class="anchored" data-anchor-id="genres"><span class="header-section-number">1.9.1.2</span> genres</h4>
<p>We adhere to the categorization provided in the corpus Metadata; to simplify some graphs, we sometimes aggregate several genres in wider categories:</p>
<p><strong>scriptures</strong> include sūtra, tantra and dhāraṇī.</p>
<p><strong>narrative</strong> includes literature and avadānas.</p>
<p><strong>other</strong> gathers genres for which we have only few/short texts in the corpus, like stotra and sādhana.</p>
</section>
<section id="thematic-categorization" class="level4" data-number="1.9.1.3">
<h4 data-number="1.9.1.3" class="anchored" data-anchor-id="thematic-categorization"><span class="header-section-number">1.9.1.3</span> thematic categorization</h4>
<p>We take 32 semantic tags as pertaining to Language and divide them into themes through qualitative analysis.</p>
<p><strong>vocabulary</strong> includes the following tags:</p>
<ul>
<li><p>“word”</p></li>
<li><p>“words”</p></li>
<li><p>“name/word”</p></li>
<li><p>“word/term”</p></li>
<li><p>“word/phrase”</p></li>
<li><p>“statement/sentence”</p></li>
<li><p>“conventional designation/name”</p></li>
</ul>
<p><strong>naming</strong> includes:</p>
<ul>
<li><p>“known as/called”</p></li>
<li><p>“name/title”</p></li>
<li><p>“conventional designation/name”</p></li>
<li><p>“name/word”</p></li>
<li><p>“name/named”</p></li>
<li><p>“name/named/called”</p></li>
<li><p>“name/called”</p></li>
<li><p>name”</p></li>
</ul>
<p><strong>verbal_expression</strong>:</p>
<ul>
<li><p>“made known/revealed”</p></li>
<li><p>“what is uttered”</p></li>
<li><p>“statement/sentence”</p></li>
<li><p>“utterance/act of speaking”</p></li>
<li><p>“exposition/formulation”</p></li>
<li><p>“statement”</p></li>
<li><p>“instruction/command”</p></li>
<li><p>“verbal expression”</p></li>
<li><p>“verbalization”</p></li>
<li><p>“speech”</p></li>
</ul>
<p><strong>conceptualization</strong>:</p>
<ul>
<li><p>“term/concept”</p></li>
<li><p>“designation_verbal expression/notion”</p></li>
</ul>
<p><strong>construct</strong> includes:</p>
<ul>
<li><p>“manner of expression”</p></li>
<li><p>“conventional designation/name”</p></li>
<li><p>“consensus (esp.&nbsp;linguistic)”</p></li>
<li><p>“consensus/convention”</p></li>
<li><p>“language usage/communication practice”</p></li>
<li><p>“usage/practical communication”</p></li>
<li><p>“nominal existence (+sat)”</p></li>
<li><p>“designation_verbal expression/notion”</p></li>
</ul>
<p><strong>sound</strong>:</p>
<ul>
<li><p>“sound of speech”</p></li>
<li><p>“utterance”</p></li>
</ul>
<p><strong>non_verbal</strong>:</p>
<ul>
<li><p>“signal/gesture”</p></li>
<li><p>“mark/sign”</p></li>
</ul>
<p><strong>literality</strong>:</p>
<ul>
<li><p>“words” (for <em>ruta</em> only)</p></li>
<li><p>“phoneme/letter”</p></li>
</ul>
<p>Two tags are included in multiple themes, “designation_verbal expression/notion” and “conventional designation/name”. “designation_verbal expression/notion” tags cases where prajñapti points to unsubstantiality and conceptually constructed character of words. This pertains both to the theme of language as construct (e.g.&nbsp;<em>Samādhirāja</em>, 3345: “prajñapti-vyavahāraḥ yad idaṃ loka vyavahāraḥ”; “What is the use of designations? It is worldly usage” [Roberts/84000 40.66-67]), and to that of language as conceptualization (e.g.&nbsp;<em>Abhidharmakośabhāṣya</em>, 6416: “na ca saṃsthānaṃ paramāṇau vidyate dīrgh^ādi / tasmād bahuṣv eva tathā saṃniviṣṭeṣu dīrgh-^ādi-prajñaptiḥ / atha mataṃ saṃsthāna-paramāṇava eva tathā saṃniviṣṭā dīrgh-^ādi-saṃjñāṃ labhanta iti /”; “There is no atom of length. […] Therefore what we designate as long is a number of real things,—atoms of color,—arranged in a certain manner.” [Pruden 557-8]).</p>
<p>“conventional designation/name” tags cases where <em>saṃketa</em> refers to a word. Given that the socially constructed nature of assigning names to things is intrinsic in the meaning of <em>saṃketa,</em> this tag applies equally to the “vocabulary”, “naming” and “construct” themes.</p>
<p>For the theme overview graph we have counted “conventional designation/name” under “vocabulary” and ““conventional designation/name” under construct.</p>
</section>
<section id="ai-tags-quality" class="level4" data-number="1.9.1.4">
<h4 data-number="1.9.1.4" class="anchored" data-anchor-id="ai-tags-quality"><span class="header-section-number">1.9.1.4</span> AI tags quality</h4>
<p>Some tags yielded poor results in our formal evaluation; notably tags pertaining to minority senses of the lemmata <em>saṃjñā</em>, <em>ruta</em>, <em>saṃketa</em>, <em>śabda</em> and <em>vacana</em>.</p>
<p><code>*saṃjñā* in the sense of 'called'</code>, used for the aspect of Language as naming, only was correctly tagged 50% of the times out of 31 cases in the gold-standard dataset we used for evaluation. Many cases were instead tagged as ‘term/concept’, which we used for Language as vocabulary and Language as conceptualization.</p>
<p><code>*ruta* in the sense of sound of speech</code>, which is conflated with the sense ‘sound’, does not pertain to Language and is therefore not considered in this portrait. It is important to note that the gold-standard dataset we used for evaluation only contains 7 instances of this tag, so the accuracy score is not very reliable due to paucity of data.</p>
<p><code>*śabda* in the sense of 'utterance*</code>, which points to cases where the lemma denotes the vocal/sound aspect of language, is often conflated with cases were the lemma means sound. Again this is a minority sense with only 15 cases recorded in our gold dataset, so accuracy statistics are unreliable and the overall tagging quality may well be better than our accuracy score suggest. Still, we have therefore avoided quantitative analysis of Language as sound, since the tagging accuracy scores for both <em>ruta</em> and <em>śabda</em> are low for this sense.</p>
<p><code>*saṃketa* senses of mark/sign and consensus</code> have been heavily conflated with the main sense of this lemma as conventional designation. Again, the formal evaluation of these low-frequency senses is not very reliable, as the gold-standard dataset only has 3 and 6 sentences for these senses respectively. This affects our section on Language as nonverbal, where the tag “mark/sign” is relevant. It does not affect discussion of Language as construct, as the tags “consensus” and “conventional designation” have been merged for that analysis.</p>
<p>Finally, <code>*vacana* in the sense of instruction/command</code> yields the very poor score of 0% correct tags, but this sense is only evaluated against 4 cases in the gold-standard dataset, so actual accuracy may be much higher. Still, this does not affect the analysis in this portrait, since we merged this tag with the tags “statement” and “utterance/act of speaking” for the section on Language as verbal expression.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>frequency of words meaning word, by genre</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 54%">
<col style="width: 15%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">lemma</th>
<th style="text-align: center;">tag</th>
<th style="text-align: center;">Correct</th>
<th style="text-align: center;">dataSize</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">pada</td>
<td style="text-align: center;">word/phrase</td>
<td style="text-align: center;">1.0000000</td>
<td style="text-align: center;">31</td>
</tr>
<tr class="even">
<td style="text-align: center;">pada</td>
<td style="text-align: center;">statement/sentence</td>
<td style="text-align: center;">1.0000000</td>
<td style="text-align: center;">31</td>
</tr>
<tr class="odd">
<td style="text-align: center;">saMjJA</td>
<td style="text-align: center;">name/named/called</td>
<td style="text-align: center;">0.5000000</td>
<td style="text-align: center;">147</td>
</tr>
<tr class="even">
<td style="text-align: center;">saMjJA</td>
<td style="text-align: center;">term/concept</td>
<td style="text-align: center;">0.9400000</td>
<td style="text-align: center;">147</td>
</tr>
<tr class="odd">
<td style="text-align: center;">saMjJA</td>
<td style="text-align: center;">signal/gesture</td>
<td style="text-align: center;">1.0000000</td>
<td style="text-align: center;">147</td>
</tr>
<tr class="even">
<td style="text-align: center;">AkhyAta</td>
<td style="text-align: center;">made known/revealed</td>
<td style="text-align: center;">1.0000000</td>
<td style="text-align: center;">25</td>
</tr>
<tr class="odd">
<td style="text-align: center;">AkhyAta</td>
<td style="text-align: center;">known as/called</td>
<td style="text-align: center;">1.0000000</td>
<td style="text-align: center;">25</td>
</tr>
<tr class="even">
<td style="text-align: center;">akSara</td>
<td style="text-align: center;">what is uttered</td>
<td style="text-align: center;">0.8333333</td>
<td style="text-align: center;">14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ghoSa</td>
<td style="text-align: center;">sound of speech</td>
<td style="text-align: center;">0.9534884</td>
<td style="text-align: center;">70</td>
</tr>
<tr class="even">
<td style="text-align: center;">ruta</td>
<td style="text-align: center;">sound of speech</td>
<td style="text-align: center;">0.0833333</td>
<td style="text-align: center;">33</td>
</tr>
<tr class="odd">
<td style="text-align: center;">ruta</td>
<td style="text-align: center;">words</td>
<td style="text-align: center;">0.6666667</td>
<td style="text-align: center;">33</td>
</tr>
<tr class="even">
<td style="text-align: center;">upacAra</td>
<td style="text-align: center;">manner of expression</td>
<td style="text-align: center;">0.8965517</td>
<td style="text-align: center;">82</td>
</tr>
<tr class="odd">
<td style="text-align: center;">vacana</td>
<td style="text-align: center;">statement/sentence</td>
<td style="text-align: center;">1.0000000</td>
<td style="text-align: center;">22</td>
</tr>
<tr class="even">
<td style="text-align: center;">vacana</td>
<td style="text-align: center;">word</td>
<td style="text-align: center;">0.6666667</td>
<td style="text-align: center;">22</td>
</tr>
<tr class="odd">
<td style="text-align: center;">vacana</td>
<td style="text-align: center;">instruction/command</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">22</td>
</tr>
<tr class="even">
<td style="text-align: center;">vacana</td>
<td style="text-align: center;">utterance/act of speaking</td>
<td style="text-align: center;">0.8333333</td>
<td style="text-align: center;">22</td>
</tr>
<tr class="odd">
<td style="text-align: center;">vyaJjana</td>
<td style="text-align: center;">phoneme/letter</td>
<td style="text-align: center;">0.9807692</td>
<td style="text-align: center;">64</td>
</tr>
<tr class="even">
<td style="text-align: center;">zabda</td>
<td style="text-align: center;">word</td>
<td style="text-align: center;">0.7741935</td>
<td style="text-align: center;">77</td>
</tr>
<tr class="odd">
<td style="text-align: center;">zabda</td>
<td style="text-align: center;">utterance</td>
<td style="text-align: center;">0.1250000</td>
<td style="text-align: center;">77</td>
</tr>
<tr class="even">
<td style="text-align: center;">nAman</td>
<td style="text-align: center;">word/term</td>
<td style="text-align: center;">1.0000000</td>
<td style="text-align: center;">89</td>
</tr>
<tr class="odd">
<td style="text-align: center;">nAman</td>
<td style="text-align: center;">name/title</td>
<td style="text-align: center;">1.0000000</td>
<td style="text-align: center;">89</td>
</tr>
<tr class="even">
<td style="text-align: center;">prajJapti</td>
<td style="text-align: center;">designation_verbal expression/notion</td>
<td style="text-align: center;">0.9625000</td>
<td style="text-align: center;">128</td>
</tr>
<tr class="odd">
<td style="text-align: center;">prajJapti</td>
<td style="text-align: center;">nominal existence (+sat)</td>
<td style="text-align: center;">0.3000000</td>
<td style="text-align: center;">128</td>
</tr>
<tr class="even">
<td style="text-align: center;">prajJapti</td>
<td style="text-align: center;">exposition/formulation</td>
<td style="text-align: center;">0.8529412</td>
<td style="text-align: center;">128</td>
</tr>
<tr class="odd">
<td style="text-align: center;">saMketa</td>
<td style="text-align: center;">conventional designation/name</td>
<td style="text-align: center;">1.0000000</td>
<td style="text-align: center;">29</td>
</tr>
<tr class="even">
<td style="text-align: center;">saMketa</td>
<td style="text-align: center;">mark/sign</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">29</td>
</tr>
<tr class="odd">
<td style="text-align: center;">saMketa</td>
<td style="text-align: center;">consensus/convention</td>
<td style="text-align: center;">0.0000000</td>
<td style="text-align: center;">29</td>
</tr>
<tr class="even">
<td style="text-align: center;">vyavahAra</td>
<td style="text-align: center;">language usage/communication practice</td>
<td style="text-align: center;">0.9054054</td>
<td style="text-align: center;">278</td>
</tr>
</tbody>
</table>
</div>
</div>


</section>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><em>yena rūpam ity evam ādinā&nbsp;nāmnā te rūp-^ādi-saṃjñakā dharmā abhilapyante ’nuvyavahriyante rūpam iti vā vedan^eti vā vistareṇa yāvan nirvāṇam iti vā /</em>&nbsp;[*<em>Bodhisattvabhūmi*,</em>&nbsp;786](By whatever names-such as those of ‘form,’ etc.—the entities known as form, etc., are expressed and verbally described—[that is, the entities that are expressed by the names] ‘form,’ ‘feeling,’ [and so on] at length up to ‘nirvana’ […].” [Engle 85])<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><em>vastu-svabhāv-^ābhidhāna-mātraṃ nāma viśiṣṭa-vastu-svabhāv-^ābhidhānam padam iti /</em> <a href="&quot;Thus, a name merely states the essence of an entity, while an assertion states the distinguishing characteristics that pertain to an entity's essence.&quot; [Engle]">*<em>Pañcaskandavibhāṣa*</em>, 1869</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><em>an-ant^eti śāradvatīputra a-paryanta-vacanam&nbsp;etat /</em>&nbsp;<a href="&quot;… endless that is another word for boundless.&quot; [Conze]">*<em>Suvikrāntavikrāmiparipṛcchā*</em>,&nbsp;965</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><em>yaṃ dvitīyā sukh^opapattir iti ayam atra tadyathā-śabdo dṛṣṭānta-vācaka iti yukta etasmāc cheṣa-saṃpratyayaḥ /</em>&nbsp;[*<em>Abhidharmakośabhāṣya*</em>,&nbsp;75](“In the two passages given above the word tadyathā is used to introduce an example. We must translate tadyathā not as ‘namely’ but as ‘for example’. It is a rule concerning examples that when one names one case one designates all similar cases.” [Pruden 237])<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><em>rut-^ānyatvāt na c^āsya&nbsp;yathārutam arthas tasmān na yathārut-^ārth-^ānusāreṇ^edam a-buddha-vacanaṃ veditavyaṃ /</em>&nbsp;<a href="&quot;'Because it has more to it than words;’ its import is not just its literal meaning. Therefore, adherence to its literal meaning cannot support the notion that it is not the word of the buddha.&quot; [Thurman 8]">*<em>Mahāyānasūtrālaṃkāra*</em>,&nbsp;64</a><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><em>yaḥ pitta-dāhena vidahyamānaḥ śīta-kriyāṃ bhoga iti vyavasyet / duḥkha-pratīkāra-vidhau pravṛttaḥ kāmeṣu kuryāt sa hi bhoga-saṃjñām // 11 — 40 //</em>&nbsp;[*<em>Buddhacarita*</em>,&nbsp;777](“A man who, as he’s burning with bilious fever, decides ‘cold remedies are enjoyments,’ He, indeed, while using remedies for suffering, would give the name ‘enjoyment’ to pleasures.” [Olivelle 311])<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p><em>udak-^ārambaṇen^ā-bhūtasya meghasy^ānutpann-^ā-niruddhasy^ā-sato megha-prajñaptiḥ&nbsp;sthitā loke megha iti /</em>&nbsp;<a href="&quot;Mañjuśrī, when some water is taken as a point of reference for an unreal cloud that has not arisen nor ceased, and is non-existent, the designation ‘cloud’ is established in the world.&quot; [Salvini/84000: Translating the Words of the Buddha 1.36]">*<em>Jñānālokālaṃkāra*,</em>&nbsp;34</a><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p><em>loka-prasiddham ekasmāt parikalpita-svabhāvāt / yasmin vastuni&nbsp;saṃketa-saṃstav-^ānupraviṣṭayā buddhyā sarveṣāṃ laukikānāṃ darśana-tulyatā bhavati / pṛthivy ev^eyaṃ n^āgnī rūpam ev^edaṃ na śabda ity evam ādi /</em>&nbsp;[*<em>Madhyāntavibhāgabhāṣya*</em>,&nbsp;42](“‘That which is accepted by the world at large is due to the one’ the constructed own-being, in which, regarding its range of events, there is a certain sameness of views among all worldly people because their intellects have adapted themselves with acquaintance to certain conventional symbol, e.g.&nbsp;‘this is earth, not fire’, ‘this is a visible, not a sound’, etc.” [Anacker 237])<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>For this analysis we have included in the senses of prajñapti as expressing “language as construct” cases where <em>prajñapti</em> is explicitly about ontology and is contrasted with <em>dravya</em>, and cases where it has the more general meaning of verbal expression or notion superimposed on ultimately unreal phenomena. We had included the latter word-sense in our analysis of Language as conceptualization, where <em>prajñapti</em> featured together with <em>samjñā</em>. When plotting all aspects of language here, we only retain <em>saṃjñā</em> for the domain of conceptualization and count <em>prajñapti</em> in the sense of notion as part of language as construct.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>anupūrveṇa racit^ānupūrveṇa samāyuktā pratirūpair nāma-kāya-pada-kāya-<strong>vyañjan</strong>a-kāyair ; yad uta teṣāṃ teṣām arthānāṃ sūcanāya kuśalānām arth^opasaṃhitānāṃ brahmacary^opasaṃhitānām / (<em>śrāvakabhūmi</em> śbhi 228: “[…] and those who established the canon, having received that account, arranged it in order and connected it in order, as proper, with beautiful sets of intensional definitions, extensional definitions, and syllables, namely, so as to indicate such and such meanings and virtues associated with aims and associated with chastity—that is called sūtra.” [Wayman 76])<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>